### ISSUE TITLE
Whitespaces in Dublin Core elements

### ISSUE THREAD

**Issue by gromnitsky** [johnfactotum/foliate#1001]
**Question:**

Is there a specific reason for preserving whitespaces in Dublin Core nodes? According to the EPUB 3.3 spec,

> "Whitespace within these element values is not significant. Sequences
> of one or more whitespace characters are collapsed to a single space
> [infra] during processing"

But Foliate doesn't strip leading & trailing whitespaces? E.g., if an EPUB have the following in an .opf file:

~~~
<dc:identifier id="bid">
  urn:uuid:a62fb22f-c826-4953-8aee-f772462705aa
</dc:identifier>
~~~

Foliate renders it in "About This Book" dialog as:

![1](https://user-images.githubusercontent.com/250919/226416485-5d68cb18-7fad-4a5a-8d0a-750eae18168c.png)

vs. in case of `<dc:identifier id="bid">urn:uuid:...</dc:identifier>` as

![2-proper](https://user-images.githubusercontent.com/250919/226416625-aeb8edcc-ca3f-4c0f-a6e7-01cb14f03a6d.png)

The similar behaviour can be observed for `<dc:title>` & co.

**Version:**
 - Foliate 2.6.4:
 - OS/Distribution and version: Fedora 37

**Comment by johnfactotum** [comment]
Yes, this is an Epub.js bug. Though I believe it does trim leading and trailing spaces from the unique-identifier if you get it from `book.packaging.uniqueIdentifier`, which is what Foliate uses to identify the book since e40a73f9f1d9cdf7c0fc2f6e2facb1d4873c51cb (this is different from what's displayed in the "About This Book" dialog).

Note that EPUB 3.3 is a draft and not finalized yet. In EPUB 3.2 it only says "trim" but there was no requirement to collapse white space, which was added in https://github.com/w3c/epub-specs/commit/4f841dca6ac50a2797e58f7f345ffb350481ec4c.

Anyway, the issue has been fixed in the new renderer (#962) in the `gtk4` branch. Although you do make me realize that the way it normalizes whitespace now is actually incorrect, as it uses `String.prototype.trim()` and `\s`, which will strip and collapse non-ASCII spaces as well, not just ASCII ones. A further issue is that it only replaces *two* or more consecutive whitespace characters as opposed to "*one* or more" defined by the spec.
