### ISSUE TITLE
Scrolled mode sticks at the end of chapters/sections.

### ISSUE THREAD

**Issue by chipshopness** [johnfactotum/foliate#1119]
**Describe the bug**

Cannot scroll to the next chapter in scrolled mode.

**To Reproduce**

Scroll to the end of the current chapter (or title page, index, etc). Can't scroll any further. Doesn't skip to the next chapter.

**Expected behavior**

Jump to next chapter when I hit the end of the current one. I think this was the behaviour with previous versions?

**Version:**
 - Foliate version: 3.00
 - OS/Distribution and version: Ubuntu 23.10
 - Desktop environment: GNOME 45.0
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
This is currently the expected behavior.

If you're talking about continuous scrolling, i.e. simultaneously displaying multiple sections, the new renderer doesn't support that yet.

And if you're talking about automatically going to next chapter in the non-continuous scrolling mode (calibre does something similar IIRC), that behavior was changed in v2.0 (27909890313efdbc16bf92721ffd102ce22ec31e).

**Comment by chipshopness** [comment]
Sorry, my bad. The new sideways movement of paged mode made me think I'd been using scrolled mode before. Is there any way for me to disable the sideways animation as I find it oddly and queasily disorienting?

**Comment by johnfactotum** [comment]
There isn't a way currently but I will surely add it in the next release.

**Comment by chipshopness** [comment]
Thanks for that, and for Foliate in general! I've rolled back to the last v2.0 release for now.
