### ISSUE TITLE
Cannot add Standard Ebooks OPDS feed

### ISSUE THREAD

**Issue by archisman-panigrahi** [johnfactotum/foliate#1173]
**Describe the bug**
I tried adding [Standard Ebooks OPDS](https://standardebooks.org/feeds), but nothing happens. There was no error message in terminal either.

**To Reproduce**
1. Go to Add Catalog
2. Add the link https://standardebooks.org/feeds/opds

**Expected behavior**
Standard Ebooks should be added to the catalog

**Screenshots**

**Version:**
 - Foliate version: 3.0.1+latest_code (https://github.com/johnfactotum/foliate/commit/9ad5224689d248245155c63ae52b7a3d41f37cdd)
 - OS/Distribution and version: EndeavourOS
 - Desktop environment: KDE
 - Installation method: AUR

**Comment by johnfactotum** [comment]
It's not implemented yet.

**Comment by johnfactotum** [comment]
List of unimplemented stuff that I can think of at the moment

- [x] add/edit/remove catalogs
- [x] loading and error screens
- [x] pagination
- [x] full entries
- [x] indirect acquisition
- [x] open book after downloading
- [ ] reload
- [ ] context menu
- [ ] fix acquisition menu overflow with long labels
- [ ] links to start, shelf, etc.
- [ ] show feed icon/author/updated time
- [x] show author and price in acquisition feeds
- [x] primary style for first acquisition button
- [x] ~force color and background on the summary/content in dark mode~ not applicable now that we forbid inline styles in description
- [ ] get theme colors from GTK; this will also make it possible to enable navigation gestures; can't enable it now because the webpage/webview has transparent background
- [x] OPDS 2.0
- [x] search in OPDS 2.0
- [x] set image dimensions (OPDS 2.0 only)
