### ISSUE TITLE
[Feature request] Add a ebook galerie

### ISSUE THREAD

**Issue by linuxr01** [johnfactotum/foliate#119]
Is it possible to import all ebooks in a galerie? Its more user friendly if we dont need to open the file. Just click on the ebook cover and read.

Maybe code from this app helps. https://flathub.org/apps/details/com.github.babluboy.bookworm

Example:
![grafik](https://user-images.githubusercontent.com/49744994/60996001-0ea84580-a354-11e9-9788-c4d177461bd2.png)

**Comment by johnfactotum** [comment]
Related to #69

**Comment by Tids** [comment]
It would be nice to utilize [gnomes tracker](https://wiki.gnome.org/Projects/Tracker/), since that provides most of the stuff needed already. :+1:

**Comment by itprojects** [comment]
> most of the stuff needed already.

@Tids What is it? What do you really think you need?
If you do want a cataloguing app that uses the gnome tracker, try gnome-books first.
Here's some of their features:
- you cannot directly open an individual book, because of the tracker
- gnome tracker only tracks Documents folder
- when there's a bug in gnome tracker, then there's is no reading, until fixed in both tracker and app

**Comment by Tids** [comment]
> What is it?

Like a metadata based store, where you already get the author and so on?
> you cannot directly open an individual book

why not? I see that for example the lollypop player can use tracker and still open music, when I click on it via file explorer
> gnome tracker only tracks Documents folder

Wait, that can't be true. I can find just everything in my home, except for hidden folders in tracker
> when there's a bug in gnome tracker, then there's is no reading

But then you could fallback to open your ebooks with a rightclick > open with (or just a simple click, if its the default app).

> try gnome-books first.

gnome-books is missing much more. I don't think that this is because of tracker, but because of a lack of developers on that app.

But after all it was a suggestion, not a "you better do this or I'll hate this project" :smile:

**Comment by itprojects** [comment]
There is already a metadata store in Foliate. It's in:

`~/.local/share/com.github.johnfactotum.Foliate`,

in the shape of files with JSON meta.

It's quite quick and remembers books by internal UUIDs, so even if you move or rename your book, all your meta and notes, bookmarks and highlights are safe. This  amazing feature beats the tracker in every way. Hidden folders - no problem. No need to learn a new API or to maintain compatibility with it's changes.

> But after all it was a suggestion, not a "you better do this or I'll hate this project"

All good - no problems, just bug reports :D

**Comment by johnfactotum** [comment]
I think using the JSON files currently stored in `~/.local/share/com.github.johnfactotum.Foliate` would be good. The main problem is that it does not currently store file locations (URIs). It's probably best to store file URIs in a separate file, because you might not want to sync that since it would contain URIs that would likely to be different across devices. If the an item's URI is no longer valid, the user would be given the option to select a new location or delete the entry.

And then we can use Tracker (or any other file indexing mechanism) to optionally augment it.
- Since Tracker supports extracting identifiers from EPUB books, we can use the data stored in `~/.local/share/com.github.johnfactotum.Foliate` as the main source of data to display a book gallery, and then use Tracker to get the file URIs.
- In addition to books that are recorded in `~/.local/share/com.github.johnfactotum.Foliate`, we can display additional books discovered by Tracker.
- Alternatively, we (or the user) can choose to only display books indexed by Tracker.
- If Tracker is not available or does not have info on a file, then we will simply fallback on the manual URI store.

One thing to note is that `tracker-extract` doesn't support Mobipocket and Kindle books, meaning that while it will track those files, it cannot read their metadata.

**Comment by anthonyajumelles** [comment]
@johnfactotum make sure you claim the bounty!

https://www.bountysource.com/issues/76778055-feature-request-add-a-ebook-galerie
