### ISSUE TITLE
Pages left in chapter

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#122]
Suppose you're reading in full-screen, with no progress-bar, is there any way to track the remaining page/s progress? Here one page could be both dual-layout or single, in the sense of page-flips (or space bars!).

For example, mupdf displays the page you're on, and how many are left (1/124 page). Yes, mupdf will change the count of total pages, if the dimensions change, however chances are your full screen size will be the same.

**Comment by johnfactotum** [comment]
1. There's currently no easy way of getting the current/total page number in Epub.js
2. Faking page numbers for reflowable documents isn't very useful, because they are not real page numbers
3. Whether it's showing percentage, page, or whatever, you would still need to have a progress bar in order to display it. It doesn't make sense to ask, "how do you track the progress without the progress bar?" If you want to see progress, then you _must_ enable the progress bar.

**Comment by itprojects** [comment]
If it isn't possible, then bug closed.
Why ask: "how do you track the progress without the progress bar?", this is best explained in https://github.com/johnfactotum/foliate/issues/4#issuecomment-508715869 .
