### ISSUE TITLE
The book opened by foliate is different from which I clicked

### ISSUE THREAD

**Issue by chenkeao** [johnfactotum/foliate#1231]
**Describe the bug**
I opened a epub book and closed the foliate. However, when I clicked it again from library, another book that is not added to library was opened.

**To Reproduce**
1. open a new book
2. return to library
3. open again the book

**Screenshots**
the book I wanted to open
![image](https://github.com/johnfactotum/foliate/assets/117329106/604163c6-8477-4061-a9b2-adf16e8858a5)

the book in fact opened 
![image](https://github.com/johnfactotum/foliate/assets/117329106/bf6b1438-c2be-4495-b8ca-3fa7d0a56a92)

**Version:**
 - Foliate version: 3.1.0
 - OS/Distribution and version: [Arch Linux]
 - Desktop environment: [gnome 45.3]
 - Installation method: [pacman]

**Comment by johnfactotum** [comment]
It's probably because Tracker has indexed another book that has the same identifier. See #435. To workaround this, either disable Tracker by uninstalling `tracker3-miners` or removing search locations from Settings (gnome-control-center), or edit the books so that they have different unique identifiers.

**Comment by chenkeao** [comment]
I used Sigil to check the identifiers of two books, but I find such identifiers are different.
![image](https://github.com/johnfactotum/foliate/assets/117329106/68433efe-3565-4136-b3e7-26be4f022359)
![image](https://github.com/johnfactotum/foliate/assets/117329106/6dbe6f10-5c75-46ce-82a2-eaa25916e4bd)

In addition, installing foliate from flatpak can get around this problem, but cause another problem that the book in library after rebooting cannot be opened. How to fix this, please.

**Comment by johnfactotum** [comment]
> I used Sigil to check the identifiers of two books, but I find such identifiers are different.

One of the books probably has multiple identifiers, one of which is identical to the other book's identifier.

I suppose it's also possible that there's a bug in Foliate or Tracker. But at any rate it would be related to unique identifiers because that's how Foliate identifies books and how it queries Tracker for the file's location.

> In addition, installing foliate from flatpak can get around this problem

The fact that it doesn't happen with Flatpak confirms that this is indeed a problem related to Tracker, as the Flatapk package currently doesn't have the necessary permissions (`--add-policy=Tracker3.dbus:org.freedesktop.Tracker3.Miner.Files=tracker:Documents` plus `--filesystem` permissions for wherever you have the files saved) by default.

> but cause another problem that the book in library after rebooting cannot be opened.

That's #942. You can work around it by adding permissions for Tracker, but then you'd run into the same bug where Tracker returns the wrong book.
