### ISSUE TITLE
Popup problems

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#124]
The idea of extracting footnotes and superscripts is very valuable, however it doesn't seem to work. Can you provide links to any free/libre epubs, that it works on?

**Comment by johnfactotum** [comment]
For EPUB 3 footnotes, that is, footnotes implemented using the `epub:type` attribute, there's one in _Moby-Dick_: https://github.com/IDPF/epub3-samples/releases/download/20170606/moby-dick.epub

For non-EPUB-3 footnotes, only notes on the same xhtml page is supported, and sometimes not even then (which is why it's labeled "experimental" and disabled by default). For a sample, you can download _The Federalist Papers_ here: https://bbebooksthailand.com/samples.html
