### ISSUE TITLE
When Scrolling To Read, Don't Automatically Go To Next Chapter

### ISSUE THREAD

**Issue by BrainBlasted** [johnfactotum/foliate#126]
This is a bit of the usability issue I found with the scrolling reader. While reading, a user may hit the end of a chapter without realizing it. Often their eyes are further up in the page than the bottom. This can cause the user to keep scrolling, skipping to the next chapter before they've finished the current one. I'd suggest having some sort of buffer at the end of the chapter, with a "Next Chapter" link. This way a user does not accidentally jump chapters.

**Comment by johnfactotum** [comment]
I think ideally it should display some visual indication on overscroll, and once an overscroll threshold is reached, go to the next/previous chapter.

Otherwise I agree it'd be good to have an option to disable this, and maybe disable it by default.

**Comment by johnfactotum** [comment]
Epub.js actually has a completely continuous scrolled mode (see https://futurepress.github.io/epub.js/examples/continuous-scrolled.html for a demonstration), but I couldn't get it to work with switching dynamically while reading (that is, it seems to require a complete reload to switch layouts properly).

Using that would actually be a lot better than the current scrolled view because it supports scrolling to an exact location within a chapter and getting the exact current location. And since it's completely continuous, scrolling through chapters is easy and seamless. The only downside is that it would require reopening a book to change from that view to the paginated view.

**Comment by BrainBlasted** [comment]
Are there plans for a new release soon? Would love to start using Foliate to read things, but this issue makes it very frustrating to try.

**Comment by johnfactotum** [comment]
I'm currently focusing on the rewrite, but I will consider making a release with the 1.x branch if there's a strong demand or if the rewrite ended up taking too long.

The rewrite is far from complete, but the layout switch in master is already better because continuous mode no longer requires re-opening the whole app, and scrolled mode also now supports scrolling to an exact location within a chapter and getting the exact current location.
