### ISSUE TITLE
Unable to open files via symlink

### ISSUE THREAD

**Issue by greggrossmeier** [johnfactotum/foliate#13]
My situation: I have most of my digital life (photos, music, documents, etc etc) managed using git-annex. The part of [git-annex ](https://git-annex.branchable.com/)that is important here is that it replaces the files with symlinks to a SHA'd verison of the file (so it can track changes over time).

eg:
```
greg@x1 (git)-[master] ~/annex/Books/to-sort % ls -al LearnPythonTheHardWay2ndEdition.epub 
lrwxrwxrwx 1 greg greg 204 May 31 10:11 LearnPythonTheHardWay2ndEdition.epub -> ../../.git/annex/objects/Fk/wv/SHA256E-s335707--3dcf8910fdfcbc5ce1ce4ee5b27affd117006100701614a8587de89769f19dfc.epub/SHA256E-s335707--3dcf8910fdfcbc5ce1ce4ee5b27affd117006100701614a8587de89769f19dfc.epub
```

Foliate gives an error ("Oh no! The file cannot be opened") when trying to open one of those symlinks. If I instead open the normal (non-symlink) file it works.

**Comment by HaasJona** [comment]
Something similar also happens with epub files that are mounted in Google Drive in Nautilus.

**Comment by johnfactotum** [comment]
Are you using the flatpak version? I've tested this and it seems to only happen with flatpak.

**Comment by HaasJona** [comment]
Yes, using flatpak version from flathub.

**Comment by greggrossmeier** [comment]
Same. Flatpak.

**Comment by johnfactotum** [comment]
Ah, thanks for that info. Pretty much what I suspected, as Foliate doesn't do anything special with files; it just passes the locations to Epub.js.

**Comment by HaasJona** [comment]
For the Google Drive issue you might need to add `--filesystem=xdg-run/gvfs` to the manifest.

**Comment by johnfactotum** [comment]
Actually I think flatpak is not the real blame here.

While investigating #23, I discovered that all files with [percentage-encoded](https://en.wikipedia.org/wiki/Percent-encoding) characters in their names cannot be loaded.

At first I thought this had something to do with the `encodeURI` and `decodeURI` code in Foliate, however I can also reproduce this with plain Epub.js, so it would seem there's something in Epub.js that's preventing them from loading.

This only appears to only happens with symlinks in flatpak because for symlinks the portal gives an encoded URI while for normal files it doesn't encode them.

**Comment by johnfactotum** [comment]
Is this still an issue? Can't seem to reproduce it anymore.
