### ISSUE TITLE
Equation render problem 

### ISSUE THREAD

**Issue by samuel-cavalcanti** [johnfactotum/foliate#1325]
**Describe the bug**
Foliate doesn't render the equation correctly 

**Expected behavior**
See the equation

**Screenshots**

![image](https://github.com/johnfactotum/foliate/assets/24573157/6a397609-c1dc-48aa-b35b-55fdd4e682bc)

**Expected**
![image](https://github.com/johnfactotum/foliate/assets/24573157/7379695b-8326-4096-9e7a-56c33892b1bb)

**Version:**
 - Foliate version: Flatpak 3.1.1 and archlinux 3.1.1
 - OS/Distribution and version: =archlinux
 - Desktop environment: Gnome 46
 - Installation method: Flatpak and Archlinux package

**Additional context**
The book:  [Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow: Concepts, Tools, and Techniques to Build Intelligent Systems](http://library.lol/main/E585D7EA43B3477E96A53A0BC1220F37)

**Comment by samuel-cavalcanti** [comment]
Amazing app btw !!

**Comment by johnfactotum** [comment]
Works fine for me. It's probably a problem with fonts. MathML won't render properly if the font doesn't support math. Unless you're overriding the font family with user styles, MathML would be rendered with a math font with the browser engine's stylesheet. So the problem is probably that you don't have one installed and it's falling back to a non-math font. You can use the inspector (<kbd>F12</kbd>) to see which font is using.

**Comment by samuel-cavalcanti** [comment]
![image](https://github.com/johnfactotum/foliate/assets/24573157/8f6658f5-0a43-4983-bdf7-96e2451bac5e)

![image](https://github.com/johnfactotum/foliate/assets/24573157/c4a6c8ef-0f50-4733-82d1-106492d828b2)
seems the correct font is rendering to me

**Comment by samuel-cavalcanti** [comment]
I never tooth in the foliate configuration until now.
I tried to switch the `Override Publisher Font` but it doesn't work

**Comment by samuel-cavalcanti** [comment]
FIx:  install `extra/otf-latinmodern-math` 
```shell
sudo pacman -S otf-latinmodern-math
```
you maybe should but that as a dependence
