### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by onsosb** [johnfactotum/foliate#1328]
Could you please tell me in exactly what distribution (debian based) and what version you have build this, all my attemps are failing, I am on debian bookworm.
Thanks

**Comment by johnfactotum** [comment]
It requires GTK >= 4.10 and Libadwaita >= 1.4, neither of which are available in Bookworm. Last time I built it in a Debian based distro it was Ubuntu 23.10.

**Comment by shizuo-hachi** [comment]
here is also failing to build due to gjs dependencies error (it requires a version of gjs libraries that is not on debian repositories) i'm trying to install it from other sources but the libraries seem to be co-dependent...

libgjs0g_1.80.2-1_amd64.deb
libgjs-dev_1.80.2-1_amd64.deb
libglib2.0-0t64_2.80.2-2_amd64.deb

**Comment by johnfactotum** [comment]
It's not really possible to individually update these system libraries in an old distro. Either use a container (e.g. Flatpak, Snap, etc.) or upgrade your system.
