### ISSUE TITLE
Zooming in in PDFs

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#1352]
**Question:**
Is it possible to zoom in in a PDF?

The PDFs I tried zooming in in were *probably* made into PDFs using scanners.  I am guessing that this is the issue, that the PDFs' pages are just images and Foliate is trying to zoom in by making the text in the page bigger.

**Version:**
 - Foliate version: 4.~really3.1.1-1
 - OS/Distribution and version: Debian GNU/Linux trixie/sid
 - Desktop environment: GNOME 46
 - Installation method: APT

**Comment by johnfactotum** [comment]
No, currently it's not supported. Unless you count pinch-zooming with touchscreen/-pad. This is the case for all fixed layout books.

**Comment by ghost** [comment]
Oh, I didn't know it worked with the touchpad. That is already more than enough for me, but zooming in using the mouse (in PDFs) would be great for convenience. I'm unfortunately neither familiar with JavaScript nor the GTK libraries, so I cannot make a patch.

**Comment by johnfactotum** [comment]
Well, while the problem is common to all fixed layout formats (as it's a missing feature of Foliate's fixed layout renderer), for PDFs there's also the issue of blurriness which can't be worked around with pinch zooming. That can only be fixed either by using the SVG backend in PDF.j, or by rerendering the canvas depending on the zoom level.

**Comment by ghost** [comment]
The issue of blurriness is related to the PDF itself, as you've mentioned, so I don't think it is a big of an issue. But, indeed, the first one you've mentioned is worth fixing. Like the application anyways, great work.
