### ISSUE TITLE
failed to add Calibre-web OPDS

### ISSUE THREAD

**Issue by eailfly** [johnfactotum/foliate#1366]
**Describe the bug**
When add OPDS from Calibre-web, shows Load failed\nundefined on UI, and ther's a "Failed to load resouce: Unspecified proxy lookup failure" in Console window

**To Reproduce**
1. add Calibre-web OPDS
2. See error

**Expected behavior**
See Calibre-web's OPDS

**Screenshots**
![图片](https://github.com/user-attachments/assets/3edee349-2dd7-41a0-9762-9d7aba0f3ccf)

**Version:**
System: Arch Linux rolling
Desktop: KDE
Session: KDE (wayland)
Language: zh_CN.UTF-8

- Foliate 3.1.1
- GJS 1.80.02
- GTK 4.14.4
- Adwaita 1.5.2
- GLib 2.80.4
- WebKitGTK 2.44.2

**Comment by lukehmcc** [comment]
What address are you using? Like how is this being authenticated?

**Comment by eailfly** [comment]
no authenticate needed, I can download the opds.atom file directly through web browser, the address is http://192.168.50.24:8083/opds

**Comment by lukehmcc** [comment]
Just a sanity check. Can you download it because you're already authenticated, or because your calibre web has authentication disabled? (Like does it work from a private window without any login).

**Comment by eailfly** [comment]
I can download the file using curl, so pretty sure has authentication disabled

**Comment by johnfactotum** [comment]
Does it load if you open the URL in Epiphany (GNOME Web)?

**Comment by eailfly** [comment]
this is the problem, I use KDE, have no Epiphany installed :(

**Comment by johnfactotum** [comment]
Well, the URL is fetched within the WebKitGTK WebView with a simple `fetch()`. Since the error says "Unspecified proxy lookup failure", it's probably something related to proxy, though it's unclear to me whether there is something that needs to be done in Foliate.

From what I gather (though I could be wrong), Epiphany also relies on WebKitGTK and doesn't seem have it's own proxy settings, and WebKitGTK seems to get its proxy settings from `org.gnome.system.proxy`.

So if the issue is indeed something related to proxy configuration, you can use `gsettings` to configure properties in `org.gnome.system.proxy`.

**Comment by eailfly** [comment]
since I use foliate on KDE which may cause issues hard to debug, I can leave it without opds, still thank you guys for the help
