### ISSUE TITLE
Resizing window resets current position

### ISSUE THREAD

**Issue by OlegSmelov** [johnfactotum/foliate#152]
Watch the progress bar at the bottom when window is being resized:

![foliate](https://user-images.githubusercontent.com/544537/62025824-e6d53080-b1e1-11e9-8e42-fc17739f194b.gif)

I'd expect the first line on the left page to stay the same when resized.

Foliate 1.5.3
Ubuntu 18.04.2
Used the package from https://github.com/johnfactotum/foliate/releases/tag/1.5.3

**Comment by johnfactotum** [comment]
It does try to stay on the same page after resizing, however if you then resize it again, it would try to stay on the page that you were on *after*—not *before*—your first resize.

For example:
1. Say you're at the 10th paragraph of a chapter.
2. You then resize it, making the window bigger.
3. It stays on the same page, in the sense that it would display the page that includes the start of the 10th paragraph. *But*, your location is now no longer on the 10th paragraph! Your location might now be at, for example, the 7th paragraph, because the window is big enough to display paragraph 7 to 10.
4. And now you resize it again. It tries to stay at the same location, but this "same location" now means paragraph 7, not your original location.

This is Epub.js's normal behavior and I'm not sure if there's anything I can do to improve it. There's a related upstream PR here: https://github.com/futurepress/epub.js/pull/959

**Comment by HaasJona** [comment]
A workaround might be store the current reading position only when manually switching pages and so on, not when resizing. So if you do multiple resizes in a row, always try to restore the original reading position and not the reading position that appeared after the previous resize.
