### ISSUE TITLE
Left / Right does not turn page with reading progress bar off

### ISSUE THREAD

**Issue by tonydiep** [johnfactotum/foliate#164]
On 1.4.0 left and right does not navigate previous and next page as expected when progress bar is off. (N and P does work properly)

Left and right does work properly when progress bar is on.

**Comment by tonydiep** [comment]
hm... left and right started working again.

Intermittent problem?

**Comment by johnfactotum** [comment]
The arrow keys only work when the WebView, that is, the area where the book is displayed, is focused. This is mainly because when other widgets have focus, the arrow keys, by GTK default, can be used to perform other actions such as to adjust input values or to move focus to the previous/next widget. Space and shift space also only work when the WebView is focused for the same reason.

In continuous mode (available in master) and scrolled view, the behavior of arrow keys, space, page up/down, etc. is set by WebKitGTK itself, and so they also only work when the WebView is focused.

N, P, and H, J, K, L, on the other hand, are set application-wide, because normally they don't conflict with anything else (although it does cause [some problem with the devtool](https://github.com/johnfactotum/foliate/issues/147#issuecomment-514506446)).
