### ISSUE TITLE
Font size won't change

### ISSUE THREAD

**Issue by skyblue002** [johnfactotum/foliate#173]
On Foliate, on Manjaro Linux, both the version from the repositories and the git version from AUR, the font size refuses to adjust. Clicking on "-" or "+" on the toolbar does nothing to change the font, though the number will change in increments of 0.5. Bringing up the font selection dialog won't change the font size, either. However, if "use publisher font" is turned off, the font itself can be changed.

When running the app from the command line, no output is given that seems to hint to the source of this problem.

**Comment by johnfactotum** [comment]
Although I can't say for sure without having the actual file, this is probably caused by the book itself hardcoding the font size.

Currently Foliate only overrides font-size on `body` and `p` with `!important`. It would help if you can share the file, or look at its stylesheet and see what's preventing the font size from changing.

Generally, it's kind of hard to strike a balance between user control and publisher control. I guess we could always add more granular options, but I don't want to make it too complicated to configure. Especially when in the case of the book hardcoding things, it should really be considered "a book that doesn't support changing font size," rather than "the reader doesn't support changing its font size".

**Comment by skyblue002** [comment]
I extracted all the source files from the .epub and the only font-size specifications I found in the .css file were relative (i.e. "small" as opposed to "12pt"). When I opened the .html files in Firefox and pressed Ctrl++ and Ctrl+- to change the zoom level, the fonts resized appropriately, maintaining their relative sizes as specified in the .css file. I would expect that to happen in Foliate, as well.

Just to be thorough, I also opened up this same .epub file in the ebook viewer that ships with Calibre. I was able to adjust the font sizing without issue using that app.

**Comment by johnfactotum** [comment]
Thanks for that info. `small` is kind of the problem right there.

`xx-small`, `x-small`, `small`, `medium`, `large`, `x-large`, `xx-large` are not relative, but _absolute-size_ keywords, based on the browser's default font size. Setting `default-font-size` should fix this specific issue.

It's probably to good to add a zoom option that uses WebKit's `zoom-level` property (see #117), which will replicate the zooming behavior in browsers.

**Comment by skyblue002** [comment]
My mistake. When I was looking up the sizing labels in a CSS guide, I saw that "smaller" was relative and assumed the rest were also relative. I typically use em values when writing CSS, so it was unfamiliar territory for me.

Thank you for taking a look at the issue and for your feedback on it. I appreciate it.
