### ISSUE TITLE
[Feature Request] Page Flip Animation

### ISSUE THREAD

**Issue by souravl** [johnfactotum/foliate#188]
Please add page flip animation.

**Comment by digitalethics** [comment]
@souravl What kind of animations from other ebook readers do you particularly like and that you could share here?

**Comment by digitalethics** [comment]
[Bookari](https://www.bookari.com/) page curl effect: 
![bookari_pagecurleffect](https://user-images.githubusercontent.com/57445091/84028774-9c8c1680-a991-11ea-836b-b6ebf4eff547.png)

**Comment by souravl** [comment]
I guess I looked at Google Play Books and found its "Use 3D effect for page turning" setting quite nice.

**Comment by gregory-opera** [comment]
Not _needed_... But it would still be a nice touch.

Linux users like pretty things, too... ;-)

**Comment by nekohayo** [comment]
Personally, beyond eye candy, I can see the appeal for this from a usability standpoint, when using features such as two-finger touchpad swipe gestures, to ensure that you've only flippe through one page at a time instead of skipping a set of pages.

As for which animation to use, instead of a skeumorphic page curl, you could do a horizontal slide animation that matches the movement of the gestures (when done with a touchpad gesture), like Epiphany does with touchpad swipe gestures to do history back/forward actions. The trickier detail here is that in Epiphany's case, it's not just animating something, but the movement matches the gesture; i.e. if you stop less than halfway through the movement, it "snaps back into place" like a rubber band; if you go over 50% of the horizontal movement, it snaps into place to complete the movement. It feels very natural in practice.

**Comment by digitalethics** [comment]
> instead of a skeumorphic page curl, you could do a horizontal slide animation that matches the movement of the gestures (when done with a touchpad gesture)

I agree with this from an aesthetic and practical point of view. In fact, most Android applications have some kind of horizontal slide animation.

**Comment by jony0008** [comment]
I haven't found this in any other Linux application and it would make reading so much more pleasant. 
Example: https://nodlik.github.io/StPageFlip/

**Comment by gregory-opera** [comment]
> I haven't found this in any Linux application and it would make reading so much more pleasant.
> Example: https://nodlik.github.io/StPageFlip/

This is _exactly_ the sort of effect that I am talking about... Sure, it's only a cosmetic enhancement - but as I said above, Linux users like pretty things too.

**Comment by johnfactotum** [comment]
Thanks for the link. Looks very cool.

The main problem with Epub.js is that each "page" is not a separate element, but rather a CSS column. So to have a flip animation is a bit more involved because you cannot transform each "page" individually like you would with separate elements.

Essentially, I think one will have to
1. Take a screenshot of the current page
2. Overlay this screenshot on top of the actual page
3. Go to the next page
4. Take a screenshot of the next page
5. Make an animation out of the two screenshots
6. Remove all the screenshots and show the actual page

**Comment by johnfactotum** [comment]
A horizontal slide animation has been added in 51ddfac39c41913c560dd5f19bc74234f29d8300
