### ISSUE TITLE
"trace trap (core dumped)  /opt/vlc-3.0/foliate/bin/com.github.johnfactotum.Foliate" after installing to a prefix

### ISSUE THREAD

**Issue by shlomif** [johnfactotum/foliate#19]
I am getting this error when running the exe:

```
[shlomif@telaviv1 ~]$ /opt/vlc-3.0/foliate/bin/com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:7133): GLib-GIO-ERROR **: 01:32:10.459: Settings schema 'com.github.johnfactotum.Foliate' is not installed
zsh: trace trap (core dumped)  /opt/vlc-3.0/foliate/bin/com.github.johnfactotum.Foliate
[crashes]
[shlomif@telaviv1 ~]$ GSETTINGS_SCHEMA_DIR=/opt/vlc-3.0/foliate/share/glib-2.0/schemas /opt/vlc-3.0/foliate/bin/com.github.johnfactotum.Foliate /home/shlomif/Download/Docs/Books/modern_svg_amelia_bellamy_royds_and_kurt_cagle.epub 
Gjs-Message: 01:32:36.393: JS WARNING: [resource:///com/github/johnfactotum/Foliate/js/main.js 1249]: reference to undefined property "atEnd"
[runs fine]
```

I used `meson build --prefix /opt/vlc-3.0/foliate` to build followed by `cd build && ninja install`.

**Comment by johnfactotum** [comment]
I don't quite follow. So it runs fine after setting `GSETTINGS_SCHEMA_DIR`? What is the issue?

**Comment by shlomif** [comment]
> I don't quite follow. So it runs fine after setting `GSETTINGS_SCHEMA_DIR`? What is the issue?

The issue is that it crashes <b>without</b> setting the `GSETTINGS` env var while it should run fine in that case. With the env var set, it runs fine.

**Comment by johnfactotum** [comment]
Foliate requires gsettings. It simply can't run without that.

**Comment by shlomif** [comment]
> I don't quite follow. So it runs fine after setting `GSETTINGS_SCHEMA_DIR`? What is the issue?

The issue is that it crashes <b>without</b> setting the `GSETTINGS_SCHEMA_DIR` env var to the value of the prefix dir location before running it. This is while it should run fine without that env var set. With just doing `/opt/vlc-3.0/foliate/bin/com.github.johnfactotum.Foliate` it crashes while other programs installed this way run fine this way. E,g: `/opt/vlc-3.0/inkscape-trunk/bin/inkscape` works.

**Comment by johnfactotum** [comment]
As far as know, Inkscape doesn't use GSettings.

I think it *is* possible to handle situations where the schemas are not installed. See [this stackoverflow question](https://stackoverflow.com/questions/13208188/how-can-i-find-out-whether-a-gsettings-schema-exists-or-not-before-attempting-to). However, as I said, Foliate requires GSettings. **It simply wouldn't function without those schemas installed.** So crashing is the expected behavior. One could store configs in a config file as a fallback, but then I would have to invent my own config system. This is very unnecessary and defeats the purpose of using GSettings in the first place.
