### ISSUE TITLE
Unable to open any books

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#195]
The following errors occur, when attempting to open any book:

(com.github.johnfactotum.Foliate:8796): Gtk-WARNING **:: GtkBox does not have a child property called name
file:///usr/local/share/foliate/assets/epub-viewer.js:275:22: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'cfiOne.path.steps')
file:///usr/local/share/foliate/assets/epub-viewer.js:321:42: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'rendition.location.start')
file:///usr/local/share/foliate/assets/epub-viewer.js:78:38: CONSOLE ERROR Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'location.start.percentage')

**Comment by johnfactotum** [comment]
I can't reproduce this. It opens fine for me.

**Comment by itprojects** [comment]
Can you install Foliate through meson build in a brand new (Ubuntu) virtual machine, that has never had Foliate?

**Comment by johnfactotum** [comment]
Honestly, I can't be bothered with vms right now. In any case it's probably nothing to do with that. There's probably something wrong with how I've currently setup epub.js. Can you describe what exactly happens when you try to open a book? If it works with previous commits, can you try using git bisect to locate the bad commit?

**Comment by itprojects** [comment]
Solved in latest commit.
