### ISSUE TITLE
[Feature Request] Disable Pop-up when mouse cursor stops.

### ISSUE THREAD

**Issue by Raphapere** [johnfactotum/foliate#196]
It would be nice to be able to deactivate this pop-up who shows up when mouse cursor stops. 

![screenshot7](https://user-images.githubusercontent.com/20495934/67349607-cab20880-f51e-11e9-8cff-8f8f2219ec81.png)

That's really annoying if you read using mouse cursor as a guide point (like a finger in a physical book).

Thanks for your work.

**Comment by johnfactotum** [comment]
This tooltip is added by the book itself. I suppose we can try to remove all `title` attributes (since there's really no way to tell which ones are useful and which ones are not), but I'm not sure if we should have an option for this. On the one hand it does sometimes get a bit annoying when books do this, on the other hand I don't want to add too many options, particularly niche and aggressive ones like this one.

Maybe we can allow the user to have a custom script executed, like userscripts in browsers, to allow more advanced tweaks. Alternatively, the user can just edit the book, or ask the publisher to remove this.

**Comment by itprojects** [comment]
It is very rare for a book implement such behaviour. Allowing userscripts will still require the user to write and test  a script, for just one book. Doesn't the whole issue fits 'not-our-bug' classification?

**Comment by Raphapere** [comment]
I just installed foliate and didn't notice that it was a problem just with this book. I'm sorry.
I will try to change the book or read this specific book on Calibre.
Thanks for your help.

**Comment by johnfactotum** [comment]
Well, I've seen at least one of two books that have this, but I'll close this for now. I still think it might be helpful to some people if there's an easy way to inject userstyles/userscripts. It can perhaps work like a sort of plugin system. Might be worth considering in the long term.
