### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by aadilayub** [johnfactotum/foliate#2]
![Screenshot from 2019-05-31 04-38-17](https://user-images.githubusercontent.com/31581044/58671976-1d1b3e80-835e-11e9-85e9-d01975a3e003.png)

The text remains displayed with a default serif font, no matter which font you choose. 

Compared to what the display should actually look like:

![image](https://user-images.githubusercontent.com/31581044/58672042-869b4d00-835e-11e9-9a59-0b7339913256.png)

I'm using this app on Fedora 30

**Comment by johnfactotum** [comment]
This happens only when a book has styles on elements other than the `<body>`, which is where the font overrides are set. In this case the book for some reason wraps all its contents in a `<div>` and sets `font-family` to `serif`, which is why it's being displayed with the default serif font.

I think this can be fixed by setting the default serif and sans-serif fonts in WebKit. This might break things, however, if, in some cases, the serif/sans-serif distinction is needed. A way to solve this would be to offer the user the option to set serif and sans-serif separately (and probably monospace, too).

That would only fix the font family, however. I'm not sure if we should also force styling using the universal selector. That might fix issues with books that hardcodes styles for no good reason, but there are cases where this would break the book's intended styling.

I think a good compromise would be:

1. Set both default serif and sans-serif font in WebKit to the user selected font

2. Force line-height with the `*` selector
There's rarely any good reason for books to hardcode that, as far as I can see. But other properties should be left untouched

3. Offer a "use default stlying" option to disable all custom styles

**Comment by johnfactotum** [comment]
This and similar cases should be fixed now. I'm a bit uneasy about using `!important` as this already breaks one of the books that I tested that for some reason uses `p` with big font-size for titles.

On balance I think this is a good compromise. 395b0b2  should fix most problems with custom styles not working.

As for a "use publisher default" setting, I'm not quite sure how that can be achieved at the moment. If anyone is interested in that or has any other styling problems, feel free to open a new issue.
