### ISSUE TITLE
Headerbar Close App Button

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#210]
Since you (@johnfactotum) are fixing headerbars, how do you feel about adding a close app button for the fullscreen headerbar? This will save the users the effort to exit full screen and close the app.

**Comment by johnfactotum** [comment]
It's intentional. Most core GNOME apps and mockups are like this; the idea is that when in fullscreen the close button (which is the only window button by default) is _replaced_ with the view restore button. Also the maximize/unmaximize button (if enabled) is broken in fullscreen.

However seeing that Builder and Web both have window buttons in fullscreen, I suppose we can add them.

**Comment by itprojects** [comment]
Thanks! It looks very nice.
