### ISSUE TITLE
Swipe to turn page skips 4 pages at a time

### ISSUE THREAD

**Issue by tokyovigilante** [johnfactotum/foliate#224]
Using 1.53 (but also occurs with git build) on FC31, ThinkPad X1 Yoga. In landscape with two pages visible, swiping to turn page skips ahead twice (ie 4 pages ahead). It can be avoided by using a tiny slide/swipe but this is very finicky.

**Comment by johnfactotum** [comment]
I assume you're referring to touchscreen swipes? Currently the code only handles the wheel event, and uses debouncing so that a single scrolling action would only turn the pages once.

https://github.com/johnfactotum/foliate/blob/22cfa61d31d1d31755c66bfa4eb962907557ba8b/src/assets/epub-viewer.js#L622-L635

https://github.com/johnfactotum/foliate/blob/22cfa61d31d1d31755c66bfa4eb962907557ba8b/src/assets/utils.js#L16-L28

I've only tested this with a laptop touchpad as I don't have any touchscreen device to test with. Actually I didn't expect the wheel event to be triggered on a touchscreen at all, and it's not clear how exactly WebKitGTK handles touch devices.

**Comment by touchscreenuser** [comment]
Worked on Arch Linux Surface Go with master branch without issues. Which distro / version of WebKit2GTK are you using?

**Comment by jthornhill** [comment]
Just a note that I also observe inconsistent swipe page turns. If I am very precise and careful to make small swipes I can seem to mostly get single page turns as @johnfactotum mentioned, but not totally reliably.

I'm running Foliate on a Dell XPS 9360 on Arch Linux using GNOME. The versions are:

extra/webkit2gtk 2.26.2-2 [installed] 
community/foliate 1.5.3-1 [installed] 

(As an aside even with this issue Foliate works relatively well on my touchscreen, when compared to other Linux ebook reading software!)

**Comment by touchscreenuser** [comment]
I use Cinnamon on Arch Linux with Foliate 2.0.0 from AUR repository.

**Comment by nvllsvm** [comment]
I've disabled the mouse wheel in epub-viewer.js so I can solely use tap to turn. https://github.com/nvllsvm/foliate/commit/ef948d64d8eafd93035b64309901e05eb08ebbd5

Similar to the "Turn page on tap" option, perhaps a "Turn page on wheel" option could be added to settings. Thoughts?

**Comment by johnfactotum** [comment]
@nvllsvm See #555.
