### ISSUE TITLE
[Feature Request] Add txt (plain text) support

### ISSUE THREAD

**Issue by R8s6** [johnfactotum/foliate#226]
Hi,

I understand pretty much any text editor can open up a txt file, but they don't support the "reading" features as foliate does, such as two-page view, spacing / margin, hotkeys to turn pages, etc.

So it would be awesome to have plain text (txt) support.

Thank you very much!

**Comment by johnfactotum** [comment]
I've added basic support for text files.

Note that annotations are currently disabled, and last location not remembered, because text files don't have unique identifiers.

Also, it treats 3 newlines or more as chapter breaks, 2 newlines as paragraph breaks, and ignores single newlines. Obviously, this works better for some text files than others.

![image](https://user-images.githubusercontent.com/50942278/79997195-cf914e00-84a8-11ea-897a-e656c29e5379.png)

**Comment by R8s6** [comment]
Thank you very much, it's awesome!
