### ISSUE TITLE
Ebook Discovery

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#253]
Currently it's not that easy to try this app unless you already have some ebooks on your computer.

It would be cool if there was an integration with one of the online repositories of quality freely licensed ebooks, (e.g. https://standardebooks.org has very nice ones), so people who don't already have an ebook collection can easily get something to read and start using the app.

**Comment by johnfactotum** [comment]
This is technically the same as https://github.com/johnfactotum/foliate/issues/6, as OPDS is the standard format for e-book discovery, and similar in motivation to https://github.com/johnfactotum/foliate/issues/218.

I suppose we can try and implement some OPDS support, or even just add links to some e-books or e-book websites on the welcome screen, which would be better than nothing for the purpose of letting the user try out the app.

**Comment by bertob** [comment]
I just built master, this is super cool!

Would you like feedback on the UI flow as it is now, should I wait until it's in a release? If so, would you perfer it in a separate issue, or  in this thread?

**Comment by johnfactotum** [comment]
Thanks! I'm actually planning on making a release right now, because 25b4df2cc5cf045c8c9daff9fb8c3e06653ef0f3 is kind of a critical security fix (for people who enable "allow unsafe content"), and it'll be easier and quicker to just make a new release than backporting it to 2.1.x.

As for opening separate issues or not, personally I think I would prefer separate issues. That way it's easier to track and reference individual points. One can always track several related issues together with links or tags, etc., but it's harder to separate them up. But either way would be fine, really.
