### ISSUE TITLE
More than two columns

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#257]
Is it possible to add column layout with three or four columns?

A kind of "speed reading" mode. The idea is that if such a feature is possible, then Foliate will resemble the narrow columns of newspapers which are easier and much quicker to read.

**Comment by johnfactotum** [comment]
See upstream issue: https://github.com/futurepress/epub.js/issues/525

**Comment by digitalethics** [comment]
A _speed reading mode_ would be an extremely helpful feature for skimming texts. Would you consider creating a PR upstream if there is enough demand for it?

**Comment by johnfactotum** [comment]
Okay, I took a look at Epub.js's code, and it's actually not hard to implement. The hard part is getting the skeuomorphic mode and the footer to work with more than two columns.

**Comment by johnfactotum** [comment]
Coming to think of it, the skeuomorphic mode probably doesn't make sense with three columns. I guess for now we'll just skip three columns and go four columns when the view is wide enough.

**Comment by itprojects** [comment]
@johnfactotum How do you trigger this 4 columns mode? What is very wide? How many pixels? 

After testing on a widescreen, the display only has two columns (in Automatic mode) with lots of space on each side.

[This link illustrates the original idea, for the columns.](https://cdn.tutsplus.com/webdesign/uploads/legacy/articles/040_css3_columns/tutimages/example2.png)

@digitalethics Did you mean something like Spritz? [Seen here](http://i2.cdn.turner.com/money/dam/assets/140228110044-spritz-speed-reading--620xa.jpg).

**Comment by digitalethics** [comment]
@itprojects I actually just picked up on your idea of facilitating speed reading. What I had in mind was a better way to quickly _skim_ through large portions of text a as a result of having three or four columns available. A dedicated speed reading function like what Spritz offers is a fascinating idea but I personally haven't experimented with. Thanks for bringing this to my attention. 

@johnfactotum It would be great to have a button available to toggle between different column views instead of columns automatically adjusting to the screen width.

**Comment by johnfactotum** [comment]
@itprojects It uses 4 columns when the width is more than double the minimum width for 2 columns. Epub.js's default value is 800px. So you need to adjust the maximum page width to 1600 or more to see 4 columns. Note that this is the window width minus the margins. Also if you've zoomed in or out, the minimum width will also change.

@digitalethics Well, currently you can just set the max width to something less than 1600 and it will never show more than two columns. The thing missing is that you cannot have two columns _and_ each column greater or equal to 800px wide. _But_, you can always choose "Single Column" if you need the content to be really wide.

It's actually getting a bit out of hand, because people want to set _all_ kinds of things, so we need options for:
- individual column settings, which can either be
  - (the current way)
    - maximum number of columns (currently configurable, but can only be 1 or 4)
    - minimum width of a column (currently not configurable; default to 400px)
  - (alternative way) just the number of columns, without automatic adjustments
- overall settings
  - maximum total width (currently configurable; default 1400)
  - the outside margin (currently configurable, in percentage points)
  - the "inside margin", or column gap width (currently not configurable)

I suppose we can split "Automatic" into "Up to 2 Columns" and "Up to 4 Columns". It'll require further patching of Epub.js, though.

**Comment by itprojects** [comment]
@johnfactotum Here is a screenshot of what's happening at 3000+ px.

Looks like a bug, but you are very right when you say that:

> I think it's probably best to reduce everything to just three options:
    max number of columns
    max width of a column
    column gap width


![1](https://user-images.githubusercontent.com/2698054/81480472-93d0e500-9219-11ea-8666-56de17d0ead9.png)

**Comment by itprojects** [comment]
@digitalethics After trying Spritz, it seems it uses a method that does not easily allow for content retention. Just like people sing a song's words, without truly understanding the lyrics. On the other hand - different people, different reading habits. Maybe you can try a book with the free alternatives of Spritz, and comment on it.

**Comment by johnfactotum** [comment]
You need to adjust the maximum page width, not the window width.

**Comment by itprojects** [comment]
Maximum page width `com.github.johnfactotum.Foliate.view.max-width` set to `250`. The window width here is much less than the screen width. Bug?

![1](https://user-images.githubusercontent.com/2698054/81499842-d51ad080-92bd-11ea-9676-0626a28673b0.png)

**Comment by itprojects** [comment]
@johnfactotum Can you post a screenshot of what the multiple column should look like?

**Comment by johnfactotum** [comment]
The "Width" setting sets the maximum total width, not column width. As you can see, it sets the total width to 250px. If you want to see four columns, you need to set it to 1600 or more.

**Comment by itprojects** [comment]
Reproduced the four columns, they look great!

Note: the window frame does have to be very wide for this to work, like you said in https://github.com/johnfactotum/foliate/issues/257#issuecomment-626197960 . You were also right about epub.js needing more work.

**Comment by sojusnik** [comment]
Any progress on this feature? Would love to read in 3 or 4 columns.

**Comment by itprojects** [comment]
Not at the moment. More support is needed from `epub.js`.

**Comment by itprojects** [comment]
Thanks.
