### ISSUE TITLE
Unexpected font color

### ISSUE THREAD

**Issue by phocean** [johnfactotum/foliate#275]
I am using the updated 2.0.0 Flathub version.

The font color gets messed with recent version of O'Reilly e-books.

Below is an example of the text color suddenly getting red:

![Capture d’écran du 2020-04-08 09-01-19](https://user-images.githubusercontent.com/4280885/78754417-bbf9c980-7977-11ea-86b2-42be85d4d5a0.png)

This happens off and on again everywhere in this e-book. Some other e-book do not have any problem at all.

To help debugging, here in the actual content of the ebook chapter:

![Capture d’écran du 2020-04-08 09-06-31](https://user-images.githubusercontent.com/4280885/78754728-45a99700-7978-11ea-9a2f-613c2b18c57a.png)

PS : very nice application, thanks a lot!

**Comment by johnfactotum** [comment]
Not sure what's causing this, but it seems to be an Epub.js problem. Also seen here: https://github.com/johnfactotum/foliate/issues/147#issuecomment-514454307

**Comment by johnfactotum** [comment]
Okay, I think I know what's going on.

The problem is that `<a id="test" />` is not valid HTML. If you have:
```html
<!DOCTYPE html>
<meta charset="utf-8">
<style>
a {
    color: red;
}
</style>
<p><a id="test" />Hello</p>
```
This will cause the text to be colored red, as the browser treats the closed anchor as a starting tag instead.

However in XHTML (you have to name it with `.xhtml`, otherwise it gets served as `text/html`), it does work.
```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
    <head>
        <meta charset="utf-8" />
        <style>
        a {
            color: red;
        }
        </style>
    </head>
    <body>
        <p><a id="test" />Hello</p>
    </body>
</html>
```
The text, in this case, is not red.

In short, this is O'Reilly's bug, which, if I'm not mistaken, has already been corrected in their more recent editions of books.

**Comment by phocean** [comment]
Ok, that makes sense.
They have not fixed in all their e-books then, because I just downloaded these ones yesterday.

I will keep an eye to see when they fix it.

Thank you!
