### ISSUE TITLE
Meta data editing [new feature request]

### ISSUE THREAD

**Issue by blueorignal** [johnfactotum/foliate#28]
Would it be possible to consider looking into adding a metadata editing capability i.e. the ability to edit/modify the author, subject, etc?

There is no urgency for this feature as this can be readily handled by existing programs [exiftools for cli and Sigil for GUI]. However it would be nice to be able to make minor metadata tweaks directly in the application while reading a book.

**Comment by johnfactotum** [comment]
Thanks for the suggestion, but this won't be easy. To implement this, it'd basically have to redo all the opening and parsing that's currently done by Epub.js.

So for technical as well as design reasons, I think this would be a wontfix.

**Comment by blueorignal** [comment]
Thank you. That makes sense.

For anyone looking for any easy to use, comprehensive, cross-platform epub editor that also allows for editing metadata have a look at https://github.com/Sigil-Ebook/Sigil.

Load your epub in Sigil, press F8 and you are ready to edit any epub metadata.

**Comment by digitalethics** [comment]
> Thanks for the suggestion, but this won't be easy. To implement this, it'd basically have to redo all the opening and parsing that's currently done by Epub.js.
> 
> So for technical as well as design reasons, I think this would be a wontfix.

Is this also the case for the rewrite?

**Comment by johnfactotum** [comment]
Yes. The situation hasn't changed. It's either that or one can try to make Epub.js output a modified file, which will probably be a lot easier, but will require one to dig deeper into Epub.js's more advanced features or internals.

So I'm not saying that it's too difficult or that it will definitely not be added, but it's just out of the current scope of the project, which is a simple viewer for EPUB-like files. To add features like PDF, editing, book management, etc., although from the user's perspective might be highly related and are simply different features to be added, would be actually more like building entirely different apps that will probably share very little code with the current app (which is why software like Calibre is often described as a "suite" of e-book software).
