### ISSUE TITLE
Arch package out of date

### ISSUE THREAD

**Issue by nguyenkien** [johnfactotum/foliate#297]
Please update it

**Comment by johnfactotum** [comment]
You should contact the package maintainers for packaging problems. The Arch Linux package is currently maintained by @jleclanche.

Arch Linux also has a proper way for users to notify the maintainers by [flagging packages](https://www.archlinux.org/packages/flaghelp/). [`foliate`](https://www.archlinux.org/packages/community/x86_64/foliate/) is already "Flagged out-of-date on 2020-04-05".

**Comment by jleclanche** [comment]
Updated, thanks for the ping.

**Comment by nguyenkien** [comment]
@jleclanche hey, please update arch package

**Comment by johnfactotum** [comment]
@jleclanche Can you update the dependency requirements?

- `iso-codes` (optional*)
- `libsoup` (optional*)
- `libhandy` (optional)
- `python` (optional)
- `gspell` (optional)
- `tracker` (optional)

The ones marked with * are especially recommended and should probably be required instead of optional.

**Comment by jleclanche** [comment]
Updated dependencies
