### ISSUE TITLE
[Bug] Keyboard timeouts

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#308]
You can always navigate to the next and the previous page with N,P.

However if you want to use Space, Backspace, or Arrow keys, then nothing happens,when you press them, if you have left the computer for 20-30 mins (no keystrokes or touch or mouse clicks). If you read quickly, all shortcuts work fine.

**Comment by johnfactotum** [comment]
Can't reproduce. Seems to work fine for me.

**Comment by itprojects** [comment]
One thing we can do is to switch the shortcuts N with Space and P with BackSpace, for testing.

**Comment by itprojects** [comment]
You may have to repeat the procedure twice points 2. and 3. to see the bug.

Reproduction:
1. Open Foliate, open a book with many chapters.
2. Open the Table of Contents.
3. Press item that you're reading (current chapter), as if to go to that location. This gives the focus to that item, turns it to highlight colour, and the menu closes. Space and BackSpace don't work anymore, until you click on the epubjs view.

Could it be that Space and BackSpace only work if the epubjs view has focus? and not the headerbar menu? This is where the switching N with Space comes in.

**Comment by johnfactotum** [comment]
Yes, you are correct that it needs the view focused to work. We can't make the shortcuts global because it would interfere with GTK's own keyboard actions (e.g. pressing Space to activate a widget). This is also how applications like Evince handles shortcuts.

The problem is mostly gone with GTK >= 3.24.17. Now menu buttons will no longer get focus. See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1596. I suppose we could disable `focus-on-click` ourselves for earlier versions, but probably best to just leave it to the default value so everything would be consistent with other GTK applications.

**Comment by itprojects** [comment]
Were you able to reproduce the bug on your machine?

What code would be necessary to test the disabling of focus-on-click? Is it just a one line fix?

**Comment by johnfactotum** [comment]
> Were you able to reproduce the bug on your machine?

I actually can't reproduce because I'm using GTK 3.24.18. Also I think it doesn't happen in fullscreen at all, even with `focus-on-click` enabled, because once the headerbar goes hidden the focus goes back to the webview. The same goes for the location popover button.

> What code would be necessary to test the disabling of focus-on-click?

You can use GTK's inspector (Control-Shift-I or Control-Shift-D) and change the `focus-on-click` property of menu buttons to see the difference.

> Is it just a one line fix?

Yeah, it just happens that all the menu buttons on the headerbar are re-using the same code, so literally one line:

```diff
diff --git a/src/window.js b/src/window.js
index 63d3579..fa1333b 100644
--- a/src/window.js
+++ b/src/window.js
@@ -732,6 +732,7 @@ const HeaderBar = GObject.registerClass({
             valign: Gtk.Align.CENTER,
             tooltip_text: text,
             image: new Gtk.Image({ visible: true, icon_name: icon }),
+            focus_on_click: false
         })
     }
     get loading() {
```

**Comment by itprojects** [comment]
`focus_on_click: false` seems to fix it.
If you wanted to support older Gtk distributions, this would do it.

**Comment by itprojects** [comment]
This happens on GTK 3.24.18, too, with Ubuntu 20.10.

If you had to change in main.js
`['view.go-next', ['n']],` and `['view.go-prev', ['p']],` with  space and backspace,
what would be the correct syntax?

Would it be `['view.go-next', [' ']],` or `['view.go-next', ['<space>']],` ?

Where did you define that space and backspace can be alternative shortcuts?

**Comment by johnfactotum** [comment]
It's actually `space`. You can find a list of key values here: https://gjs-docs.gnome.org/gdk20~2.24p-constants/. Just remove the `KEY_` part to get the code.

> Where did you define that space and backspace can be alternative shortcuts?

In `src/assets/epub-viewer.js`. But that doesn't matter, because once you've set an application shortcut, it gets captured and nothing else will get the key event.

**Comment by itprojects** [comment]
Testing a longer ePub to check.

**Comment by itprojects** [comment]
Changing to `['view.go-next', ['space']]`, and `['view.go-prev', ['BackSpace']]`, completely removes the bug. Then `p` and `n` assignments can be added to `epub-viewer.js` so that all shortcut keys work, like they should.

**Comment by itprojects** [comment]
@johnfactotum Here's the simplest way to fix it for all.

The following very minimal patches were tested for commit 57a84bfb1065b3b2aac2c4379b7e1852c41dbb23.

[patched.epub-viewer.js.txt](https://github.com/johnfactotum/foliate/files/4566828/patched.epub-viewer.js.txt)

[patched.main.js.txt](https://github.com/johnfactotum/foliate/files/4566829/patched.main.js.txt)

**Comment by johnfactotum** [comment]
1. It's not "the simplest way".
  You can assign multiple shortcuts to an action with `set_accels_for_action`, so you can set everything in `main.js` and forget about `epub-viewer.js`.
2. It's not a "fix", either.
  In fact, as I've explained before, assigning space to an application shortcut will break all the built-in GTK and WebView shortcuts, like
    - Pressing space to activate the widget in focus
    - Pressing space to scroll down in the "Scrolled" layout

**Comment by itprojects** [comment]
Which solution is more to your liking?

**Comment by johnfactotum** [comment]
The current behavior is fine.

We can't set global shortcuts for space and other keys. I've explained the reason multiple times.

It's the same way in Evince, or any other app, really.

You can just use N/P.

If you really, really don't want N/P, then just focus on the webview.
