### ISSUE TITLE
Sort and filter annotations

### ISSUE THREAD

**Issue by giscoli** [johnfactotum/foliate#318]
It would be nice to have some options to change the order of the notes. At the moment you've them in the order of addition. It can be useful to have them in the order of position in the book (it would be my personal default), and maybe also to be able to rearrange them in other ways (i.e. assigned color).

**Comment by johnfactotum** [comment]
It's now sorted based on the order of the annotated text in the book after 13e006e. I've always wanted them to be sorted. It's not been done before because GtkListBox's API is very inconvenient. Filtering by colour is also something I've always wanted to add, but again, GtkListBox/GListStore is a pain to use.

Note that it's not possible to sort them by order of addition anymore, because we don't actually save a timestamp with the note, which is admittedly, kind of an oversight.
