### ISSUE TITLE
Text moves to the right when turning the page with arrow keys

### ISSUE THREAD

**Issue by HaasJona** [johnfactotum/foliate#321]
If you repeatedly scroll a book with the arrow keys (without changing chapters) the text shifts to the right at about 1px per scrolling. This is more visible with "Realistic Shadows" enabled. At some point, it even overflows and the text on the right appears on the left side again.

To reproduce, hit the right key then the left key then the right key and so on quickly.

![Bildschirmfoto von 2020-04-27 19-34-16](https://user-images.githubusercontent.com/4310707/80402777-bb8d8800-88be-11ea-81d0-ce161ba58176.png)

Foliate 2.0.0 (from Flathub) (actually shows version 2.1.1 in about screen)

**Comment by HaasJona** [comment]
I couldn't reproduce thin on raw ePub.js btw.

**Comment by HaasJona** [comment]
Also this only only happening at 70% zoom with certain window sizes (but with all books)

**Comment by johnfactotum** [comment]
It also happens when you use other methods, e.g., N and P, or scrolling, to turn the page.

I can also reproduce this with Epub.js's demo reader: https://futurepress.github.io/epubjs-reader/ (it happens both in Firefox and Epiphany, when zoomed out to some levels)

Not sure what exactly is causing this, but since it happens only at some zoom levels, I would guess that perhaps zooming caused some kind of rounding error in whatever Epub.js is using to determine column width.

**Comment by HaasJona** [comment]
Should I file an upstream bug? I can't however reproduce the issue on the demo website you linked.

**Comment by HaasJona** [comment]
Can't reproduce this anymore. Might be fixed?

**Comment by johnfactotum** [comment]
At any rate this doesn't happen on the new renderer. Even though there is a related issue (https://github.com/johnfactotum/foliate-js/issues/2), it seems to only happen in Firefox now.
