### ISSUE TITLE
Keep last line of previous page as first line of new page

### ISSUE THREAD

**Issue by pothos** [johnfactotum/foliate#333]
FBReader had an option (at least some years ago) to have the last line(s) of the previous page overlap with the first line(s) of the new page. This was great for reading flow (and made sure that I didn't accidentially skip a page).

Is there any chance this could be implemented in Foliate or is it rather a feature that EPub.js needs to have first?

I think I configured to keep the last 2 lines with FBReader but I think 1 line would be good enough.

**Comment by johnfactotum** [comment]
Are you talking about non-paginated layouts? I don't think it'll be possible for paginated layouts.

**Comment by pothos** [comment]
Yes, paginated (the automatic mode).

**Comment by johnfactotum** [comment]
I'm going to close this for now, since to my knowledge this is pretty much impossible to do with Epub.js. You can maybe open an issue with Epub.js, if you like.

Also checkout #187. It's not exactly like what you're describing; it keeps the whole previous page rather than just one line. But it should still achieve a similar effect.

**Comment by pothos** [comment]
Sure, I see that it's rather an upstream issue.
