### ISSUE TITLE
QUESTION: How can I explicitly set in config that width=600px for an ePUB

### ISSUE THREAD

**Issue by lobaluna** [johnfactotum/foliate#350]
I sometimes test epUBs to see how will they will look in ereaders, like mine, which is width=600px (Kobo H2O). This is important to see how tables, images, etc. flow around text.

So how do I put this setting in configuration? Is this possible?

**Comment by johnfactotum** [comment]
You can't, except adjusting the window width yourself. If you want to use an exact number, you can run `gsettings set com.github.johnfactotum.Foliate.window-state width 600` and then launch Foliate. But it will still look different because of the different padding, font, rendering engine, etc. Another method is to increase the margin, which won't get you exactly 600px, but you can eyeball it a bit.

On master you can set the max width to 600 (see https://github.com/johnfactotum/foliate/issues/192). Then you need to resize the window to something wider than or equal to 600px.

**Comment by lobaluna** [comment]
Thanks, John!Complete answer and ver useful. I'll try it ASAP.El 12 may. 2020 9:13 p. m., John Factotum <notifications@github.com> escribió:
You can't, except adjusting the window width yourself. If you want to use an exact number, you can run gsettings set com.github.johnfactotum.Foliate.window-state width 600 and then launch Foliate. But it will still look different because of the different padding, font, rendering engine, etc. Another method is to increase the margin, which won't get you exactly 600px, but you can eyeball it a bit.
On master you can set the max width to 600 (see #192). Then you need to resize the window to something wider than or equal to 600px.
