### ISSUE TITLE
Make Foliate Show all Books in Folder & Open New Instance When Icon Clicked

### ISSUE THREAD

**Issue by JamesSwift** [johnfactotum/foliate#365]
Currently, if I have a book already open, and I click on the foliate icon again it just switches to the already open window. I would prefer it if it would open a new instance so I can select a book from the recent list of books.

It would also be very helpful if you could add support for foliate to show all ebooks in a certain directory (such as `~/Books`) when it is opened. You could perhaps have a tab at the top to select between `Recent` and `Library`.

**Comment by johnfactotum** [comment]
After d21809935549f9cb46bb27521074fa5910cd5ba2, it will open the library window when you launch it again. (Note that in GNOME shell, it will still switch to the window when you click on the icon, unless you enable the "Launch new instance" extension, or use middle click, or right click and select "Library".)

As for showing all ebooks in a certain directory: currently (on master) it doesn't just show recent books. It shows _all_ books (that Foliate knows about), but sorted by recency, and searchable by metadata.

**Comment by JamesSwift** [comment]
I've just built the latest version. Thank you so much, it's awsome!

**Comment by JamesSwift** [comment]
> As for showing all ebooks in a certain directory: currently (on master) it doesn't just show recent books. It shows _all_ books (that Foliate knows about), but sorted by recency, and searchable by metadata.

I know this issue is closed now, but could I ask that you please consider the directory scanning idea again? I have my `Books/*` synced automatically between devices, and I sync my foliate .json annotation files too. I exclude the `library/*` files from syncing though as my books are stored in different locations on each device, which confuses Foliate (where has the book gone?). If I could just tell Foliate to always shows books from `x` directory, then when I add a new book on one device, it will be synced over and when I open Foliate on the other device it would scan the directory and find it. Currently, I have to remember to find and open the new file on both devices.

**Comment by johnfactotum** [comment]
There's a `--add` command-line option that you can use to add books to the library. If you can get whatever you're using to sync the files to list new files (or diff the list of files yourself with some script), you can use that.

A much easier option is to use Tracker to index your files. If the file is known to Tracker then you don't need `library/uri-store.json` at all. It will just query file locations from Tracker (this is currently limited to EPUB files, though).

I don't really want to implement any kind of scanning because it's a laborious task and difficult to implement well (just look at how many issues people have with Tracker). If it ever gets implemented it will probably just use Tracker under the hood, or something similar.
