### ISSUE TITLE
Can't go to CFI when locations cache is disabled

### ISSUE THREAD

**Issue by itprojects** [johnfactotum/foliate#376]
If possible, can you add a CFI (book location) option in the search menu. At the moment that is only possible through the location menu from the navigation bar, but such capability should be more widely available. The usage of such an option would be when one is reviewing their plain/html/markdown notes and they want to go to that location, via searching for it.

**Comment by johnfactotum** [comment]
I think CFI and search should be separate. A CFI is unique. It's like in a text editor, you have "Go to line" and "Find"; you can't search for line numbers.

It might make some sense to integrate everything from TOC to CFI together into a sort of "Go To" popover, but I'm not sure if that's going to make things more usable because it's going to get too big.

**Comment by itprojects** [comment]
After a recent commit, the Save File Locations option was added. If you turn it off you cannot go to any CFI's. If you had a CFI option in the search, that would be a fix, otherwise a very important  function that Foliate has, would remain concealed...for some reason.
