### ISSUE TITLE
Change the rather awkward deb package name to just "foliate"?

### ISSUE THREAD

**Issue by stevenpusser** [johnfactotum/foliate#420]
I already do that for the MX Linux packages. It still works fine there. Why the "com.blah.blah.blah.foliate" default package name? Just "foliate" is much more in keeping with Debian policy.

**Comment by johnfactotum** [comment]
The historical reason is that the debian files were originally made for automatically building by and for elementaryOS's AppCenter, although I've not worked on that since then, so yeah, it's not needed.

But there still a couple of reasons why it's not changed to just "foliate":
- Distro packagers (like yourself) can easily change the name to whatever they want
- We've had this name since the beginning and so things just stay the way they are unless there's compelling reason to change them
- Since the deb is provided as a thrid party package not distributed by distros, it eliminates possible naming conflicts with other software (unlike official packages, where distro maintainers are responsible for resolving conflicts)

I'm not totally against it at this point; mainly just couldn't be bothered to change it.

**Comment by stevenpusser** [comment]
OK, got it. I already package it for Debian and Ubuntu users on the OBS.  The OBS can build packages for a lot of different distros from just set of source files, but I only know how to do Debian style debs.

https://build.opensuse.org/package/show/home:stevenpusser:Foliate/foliate

**Comment by apandada1** [comment]
There was already a ppa, which hosted renamed .deb packages. https://launchpad.net/~apandada1/+archive/ubuntu/foliate
