### ISSUE TITLE
Create OPDS implementation guide for supporting upstream projects

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#449]
Could you provide me with a template regarding the technical requirements for assisting upstream projects (e.g. publishers, open access networks, etc) to properly implement OPDS on their websites? I would then point them to this issue here and we can help them if necessary.

**Comment by johnfactotum** [comment]
It's not really Foliate's place to provide a OPDS implementation guide. For anyone implementing OPDS, they should just read the [OPDS specs](https://specs.opds.io/), which is really the only "technical requirement". Also look at Feedbooks' OPDS feed for examples.

Also note that Foliate as it currently stands doesn't even properly support many OPDS features. There are also other OPDS clients that are much more mature than Foliate. When implementing OPDS, one should take them into consideration, rather than focusing on Foliate.

I think the reason people don't have well maintained OPDS feeds for their sites is simply lack of interest or resources. It's not unlike the demise of RSS feeds.

**Comment by digitalethics** [comment]
> For anyone implementing OPDS, they should just read the [OPDS specs](https://specs.opds.io/), which is really the only "technical requirement".

Thanks, this is actually already what I was looking for to point people to in case they are interested.

**Comment by digitalethics** [comment]
FWIW, there's an [OPDS Primer](https://www.feedbooks.com/api/primer) by Feedbooks and the excellent [Introduction](https://opds.io/index.html) by the OPDS Working Group.
