### ISSUE TITLE
OPDS Previews from local calibre lib. not populated

### ISSUE THREAD

**Issue by barolo** [johnfactotum/foliate#451]
I'm using Foliate with calibre-server to access my local library [ via http://0.0.0.0:8080/opds ] but can't figure out how to pull previews, other [ android ] readers do it automatically.

**Comment by johnfactotum** [comment]
Currently you need to specify the preview URL manually. You can actually just set "http://0.0.0.0:8080/opds" as the preview URL, too, although that would make it show a list of navigation entries, rather than a list of books.

I guess we should add an option to get preview from the first acquisition feed in the catalog, though it's not clear how deep one should go in search for an acquisition feed. Then maybe there should also be a "Browse..." button, which would launch a dialog for choosing the preview page.

Another issue is that it's currently not possible to get the URL as you browse through a catalog, so there should probably be an "address bar" entry, too.

**Comment by barolo** [comment]
Yeah, it's possible to get further path from the feed, something like http://0.0.0.0:8080/opds/navcatalog/4f6e6577657374  for the newest. It will only add generic previews though

**Comment by johnfactotum** [comment]
> It will only add generic previews though

Not sure what you mean by "generic previews". If you mean it's not showing cover image thumbnails, the problem is https://github.com/johnfactotum/foliate/issues/494 (which has been fixed with 8eb7e82bafd1958abc271ddc5db635f2b975aabb).

**Comment by barolo** [comment]
That did indeed fix it, the thumbnails are of very low resolution though, blurry, that's for another issue I suppose

**Comment by johnfactotum** [comment]
Fixed with bf6f78ff1327dcf44633655bfd0f758a1356bfc8.
