### ISSUE TITLE
Double-flash when resizing windows

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#459]
Ideally there is no flash when resizing windows. Typically, I would expect it to flash once but not twice. I think this only happens with larger epubs. Without this double-flash, resizing windows would look much smoother. Peek actually didn't quite catch it as it flashes two times in either resizing direction. Is there any possibility to fix this with caching?

![doubleflash_largeepubs](https://user-images.githubusercontent.com/57445091/84792361-0b9de680-aff4-11ea-852a-6e19d5a04a11.gif)

**Comment by johnfactotum** [comment]
As far as I can tell that's because Epub.js actually does resize itself twice when maximizing/unmaximizing. And the resizes are queued so the second resize gets applied only after the first resize is completed. The same goes when manually resizing the window by dragging on the window border, which usually results in multiple resizes in a row.

Also, when resizing, there's a further relocation to maintain the current location (6a373b1e0d6d881b9d64551e02950216a9917b69), which is visually undesirable, though not as serious as the the blank flash.

Generally speaking, resizing is a very costly action, because it requires reloading and applying CSS columns to the entire section, which performs very badly on WebKit, especially when the section is long.

The easiest fix is probably hiding the view while resizing.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
