### ISSUE TITLE
Distinguish between footnote preview and text preview

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#480]
Currently, the popover describes them both as _footnote previews_ when in fact the latter is linking back to the actual text. Can this be fixed?

![footnote_preview](https://user-images.githubusercontent.com/57445091/85199311-d09afc00-b2ee-11ea-9f9c-570b90384050.gif)

Tested with: [Cicero, "Tusculan Disputations"](https://standardebooks.org/ebooks/cicero/tusculan-disputations/c-d-yonge/dist/cicero_tusculan-disputations_c-d-yonge.epub)

**Comment by johnfactotum** [comment]
In short: no. It's impossible to distinguish between them.

**Comment by johnfactotum** [comment]
While it's called "footnote preview", it's more like "preview for URLs with a hash, which is often used for footnotes and end notes, but is used for other kinds of links just as often".

The footnote preview feature is intended for books that doesn't specify `epub:type="noteref"`. Without the `epub:type` attribute, it's not possible, in general, to tell whether a link is linking to a footnote, end note, or something else. In earlier versions this feature was called "Display non-EPUB-3 footnotes in a popover" for this reason.

For links _with_ `epub:type="noteref"`, it will _always_ show a popover, whether this setting is enabled or not. So for example, if you disable "Footnote Preview" in the "Advanced" menu, with books from Standard Ebooks, it will still show preview for footnotes, but when you click on "↩︎" it will just go straight back without showing any preview.

I put a "Footnote Preview" label in the popover precisely because it often _isn't_ actually showing a footnote. This feature is extremely useful, so it's enabled by default. But since it also behaves "incorrectly" quite often, naming it "footnote preview" clarifies the intention of this feature.

---

While in general it is impossible to tell whether a link is to a footnote or not, in the case where the book sets `epub:type="backlink"`, it is clearly _not_ supposed to be a footnote. So I guess this is a bug.

Also when showing a `epub:type="noteref"` link in a popover, it should be marked simply as "Footnote". Also it should not display footnote previews for links inside `epub:type="toc"` and other navigational content unless it is explicitly marked as a foot-/end note.

In general it should just use `epub:type` more to better handle the document. Should maybe also check the `role` attribute, apart from `epub:type`.

**Comment by digitalethics** [comment]
> So for example, if you disable "Footnote Preview" in the "Advanced" menu, with books from Standard Ebooks, it will still show preview for footnotes, but when you click on "↩︎" it will just go straight back without showing any preview.

I see. This is a lot clearer to me now. 

> Also it should not display footnote previews for links inside `epub:type="toc"` and other navigational content unless it is explicitly marked as a foot-/end note.

Regarding "explicitly": I was wondering to what extent Foliate needs to balance two things: to be more _conforming_ to open epub formatting standards, yet to be more _permissive_ to compensate for a lack of formatting precision on the side of the publishers, especially since not all epubs are formatted with the same elaborateness as those from Standard Ebooks. So to what extent should Foliate make assumptions of how things should work or look like?
