### ISSUE TITLE
Improve text conversion for consumption by TTS programs

### ISSUE THREAD

**Issue by vantu5z** [johnfactotum/foliate#481]
Now lines break seems to be deleted.
Suggest to replace it by space.
Exampe:
```
Some text. Some text.

New paragraph.
New line.
```
It will be transformed to: `Some text. Some text.New paragraph.New line.`
Preferably have: `Some text. Some text. New paragraph. New line.`

**Comment by johnfactotum** [comment]
Newlines are currently transformed to `; `, I think:

https://github.com/johnfactotum/foliate/blob/00e8c783f0cd30739024b0b3a5b95500a2340cf3/src/tts.js#L101-L109

Replacing it by space is not ideal because it means block elements (e.g. titles) will be read together with its siblings as one sentence.

In general the process of extracting text for TTS is kind of bad right now, because it simply calls `Range.toString()`, which is not really a good way to do it. We should probably get a `DocumentFragment` from the `Range` and process it properly.

**Comment by vantu5z** [comment]
Yes, I agree that replacing it by space is not good idea.
Found that titles processed properly (with several ` ;`).
But other text is not and it reads together with previous sentence as one.
Idealy is to have some different delays between `DocumentFragment` depending on its type.

I try to use `RHVoice` as TTS, like this:
```
#!/bin/bash
txt="$(</dev/stdin)"
echo "$txt" >&2
rhvoice_say "$txt" &
trap 'kill $!; killall spd-say; killall RHVoice-test; killall sd_rhvoice; exit 0' INT
wait
```
`rhvoice_say` - script to run RHVoice.
`echo` - used for debug in terminal.

**Comment by johnfactotum** [comment]
Closing this in favor of #829.
