### ISSUE TITLE
Consolidate and simplify Preferences

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#487]
Accessing the settings could be streamlined by merging the _Theme_ and _Advanced_ menu entries entirely into the _Preferences_ dialog. For the latter I think a view-switcher based navigation would work better to create more width and to reduce the need to scroll. 

This would also create more space for introducing [reading modes](https://github.com/johnfactotum/foliate/issues/486) in the menu popover. 

For a subsequent design iteration you could consider reintroducing selected options from the _Preferences_ that are more _frequently_ changed such as column-view buttons (one, two, four) to be placed in the menu popover and a single day-and-night button to be placed in the header bar. All other theming and advanced settings are too infrequently changed to justify a separate menu listing in my view.

**Comment by johnfactotum** [comment]
The separation between the "Advanced" menu and the "Preferences" dialog does bother me somewhat, because there's not really that clear a distinction between the two.

In theory the "Advanced" menu is for more "book-rendering-y" things. They are also more likely to be per-books settings (if we ever get that). Technically speaking, they are all settings that affect the WebView. The "Preferences", on the other hand, is for tweaking the interface and interaction. But this distinction can be a bit tenuous, and some of the items' placement are perhaps debatable.

> This would also create more space for introducing reading modes in the menu popover.

Removing just _two_ menu items doesn't really increase the available space at all.

> a single day-and-night button to be placed in the header bar

I don't really get this, to be honest. Yes, having to make an extra click is a inconvenient if your use case is changing between just two themes frequently. But how frequent does one really need this? It increases the conceptual and technical complexity of themes, and makes accessing other themes a lot harder while only makes the "day/night" switching usage only marginally easier.

**Comment by digitalethics** [comment]
> Removing just _two_ menu items doesn't really increase the available space at all.

The _Library_ entry in the menu popover could be left out too if you decide to include the viewer/reading pane component into a main window-based view switcher as a new default single-window design. I have to think about this a bit more though so these are really not more than spontaneous ideas. Maybe the _Open..._ entry could be left out too? I know you are probably hesitating to add a button for this instead (and I think it may not even be necessary). Wouldn't it make more sense to open new books from within the library component rather than the viewer?
