### ISSUE TITLE
Consider using "note" instead of  "annotation" ?

### ISSUE THREAD

**Issue by bbblanccc** [johnfactotum/foliate#499]
While `annotate` does indicate `to add notes`, `annotation` seems to be notes added by _the authors or editors_ instead of readers. 

The `annotation` feature of foliate, in my understanding, is to help readers take down their notes, so `annotation` may be a little confusing.

**Comment by johnfactotum** [comment]
Neither "note" nor "annotation" suggests authorship.

- A "note" simply means a mark or a piece of writing.
- "Annotations" (< Latin _ad-_ "to" + _nota_ "a mark")  are notes that are _added to_ an existing document or piece of information.

For example,

- I can write down a _note_ on a piece of paper to remind myself to buy the milk. That is a "note". But it's not an "annotation".
- I can put a post-it note on a milk bottle that says "this is milk" to remind myself that it is a bottle of milk. This is also a "note", but in this case it can also be said to be an "annotation" to the bottle.

---

In Foliate, _both_ terms are used for content added by the user:

- "Annotation", in Foliate, refers to both color highlights and textual notes associated with the highlights 
- "Note", in Foliate, refers to the text added to a passage of highlighted text; because "annotation" a general term for the collective color–text entity bound to a passage of the book, to specific refer to the text and _not_ the highlighting, we use "note".

In some cases the terms are also used interchangeably.

---

A book can itself contain notes and annotations. For example,
- A book can add a section at the beginning that says,

  > Note: I would like to thank my wife, without whom this book would never have been completed.

  This is a note. It's not an annotation.

- It can also say,

  > Milk is good for you! For explanation, see [3].

  Here, the author is referencing footnote number 3, which provides detailed notes on the claim. This foot-note is a note. It's not an annotation.

- When a book is a work of translation, a passage might goes,

  > Milk<sup>[2]</sup> is good for you.

  and with a note that says

  > [2] Literally "cow's milk" In the original text.

  In this case, the translator has made an _annotation_. The note does not exist in the original document; it is _added to_ the document by the translator.

---

Since notes and annotations can both be added by the book or the user, or even a third party, the only clear way to differentiate notes from the book itself and notes added by the user, is to qualify the terms further by, for example, prepending "user" to the them, like "user annotations" or "user notes". But this makes them unnecessarily long.

In general the risk of confusing is probably pretty low. In fact, calling them "notes" would probably make things _more_ confusing, as "notes" are much, much more frequently used than "annotations" by books.

This usage of "annotations" is common and even standardized. For example, the _Open Annotation_ or _Web Annotation_ standard is used to add _additional_ notes to documents. They are naturally called "annotations" for clarity, since "notes" can refer to both notes _in_ the document and notes _on top of_ the document.

---

Note: all the above is true, I believe, for English. In other languages the situation will be different. Translators should pick the most appropriate terms for the context, and not just translating literally from the isolated English words.
