### ISSUE TITLE
Any plan to support macos platform? 

### ISSUE THREAD

**Issue by stormeyes** [johnfactotum/foliate#503]
Foliate is so amazing on my ubuntu desktop, but I also use macos at home, so I wonder if the developer has any plan to support foliate running on macos?

**Comment by johnfactotum** [comment]
It should be possible if you can get `webkit2gtk`, which is the most problematic dependency, and `gjs` on macOS. Both are on MacPorts, I think. Though I don't know their current state.

Unless someone is actively maintaining WebKitGTK for macOS and Windows, I think it might be easier to create a version of Foliate in Electron or native toolkits. Obviously that's a lot of work, but it shouldn't be too hard to create a version with basic features.

**Comment by stormeyes** [comment]
> It should be possible if you can get `webkit2gtk`, which is the most problematic dependency, and `gjs` on macOS. Both are on MacPorts, I think. Though I don't know their current state.
> 
> Unless someone is actively maintaining WebKitGTK for macOS and Windows, I think it might be easier to create a version of Foliate in Electron or native toolkits. Obviously that's a lot of work, but it shouldn't be too hard to create a version with basic features.

thank u :)

**Comment by WhyDidIHaveToDoThis** [comment]
Well, I tried and I got all the way to "set the schema directory for GSettings" and had no idea what to do. I got stuck on the error permission denied when I tried to change the directory that contained the necessary folder.

If anyone wants to do try here is what I did:
- I usually use homebrew, so I had to configure the $PATH for macports in bash.profile.
- Then I waited a long time for all the dependencies to be installed.
- I cloned the github repo to a folder, switched to that directory.
- I had to change the pyenv version to 3.11
- Instead of running meson build --prefix=/usr, i used meson build --prefix=/usr/local to avoid a read only error.

Then I have no idea what to do, I will try to run foliate in a docker desktop as mentioned in #882 

Additionally required dependencies I installed:
desktop-file-utils
gsettings-desktop-schemas

**Comment by WhyDidIHaveToDoThis** [comment]
Update: soxr is updated for ventura, was able to install all dependencies.

had to look for the schemas folder to modify the command
GSETTINGS_SCHEMA_DIR=$PWD/opt/local/share/glib-2.0/schemas /usr/local/bin/com.github.johnfactotum.Foliate

now the error i get is zsh: segmentation fault  GSETTINGS_SCHEMA_DIR=$PWD/opt/local/share/glib-2.0/schemas 

idk maybe it just hates me
