### ISSUE TITLE
Single window, simpler navigation

### ISSUE THREAD

**Issue by bertob** [johnfactotum/foliate#509]
Currently if you open a book from the Catalogs view, the book opens full-screen, but the original window is also still around and visible in the Shell overview: 

![image](https://user-images.githubusercontent.com/1908896/86350021-53fb0c80-bc62-11ea-8033-ecf57af761c8.png)

There's also no obvious way to go back to the Catalogs view, other than closing the window. The Library view has a similar but different problem, because the only way to go back from the book view to the library is via an entry in the primary menu, which is not very easy to find.

I'd propose keeping everything in a single window, and using a standard hierarchical navigation scheme with back buttons (like GNOME Books, along with most other GNOME apps). The main differences would be
- All navigation happens inside the main window
- A "back" button in the headerbar of the reader view
- The book detail view would be inside the main window with a back button, rather than a dialog. The previous/next buttons might have to be dropped in order for that to work.

In addition to being simpler and clearer, this would also have the advantage of working better in an adaptive/mobile context.

Edit: I should note that this is all based on the current behavior in master, if I'm commenting on something WIP that's going to change anyway feel free to close :)

**Comment by johnfactotum** [comment]
Related to #446.

> There's also no obvious way to go back to the Catalogs view, other than closing the window.

Currently there's indeed no other way, because the window is modal -- because the book details dialog is modal, so the only way to present a usable window (without closing the dialog, which I didn't want to do because that means losing the position in the catalog view) is to make it modal too. This can be solved by not using a dialog for the book details view.

> The Library view has a similar but different problem, because the only way to go back from the book view to the library is via an entry in the primary menu, which is not very easy to find.

The easiest fix would be to add a back button to the headerbar. It's not as nice as having everything in a single window, but might be good until I have the time (and energy) to merge everything into a single window.

> The previous/next buttons might have to be dropped in order for that to work.

I think maybe they can be kept inside the window's main area (i.e. not in the headerbar) on the sides when the window is wide enough? (Which would be the more natural placement than the headerbar, anyway.)

> Edit: I should note that this is all based on the current behavior in master, if I'm commenting on something WIP that's going to change anyway feel free to close :)

I just released 2.4.0 :)

**Comment by bertob** [comment]
> The easiest fix would be to add a back button to the headerbar. It's not as nice as having everything in a single window, but might be good until I have the time (and energy) to merge everything into a single window.

Agreed, a back button in the headerbar is also the pattern most other GNOME apps are using to go from content views back to the main view. Not exactly sure how that would work without merging all the windows into one though?

> I think maybe they can be kept inside the window's main area (i.e. not in the headerbar) on the sides when the window is wide enough? (Which would be the more natural placement than the headerbar, anyway.)

That could also work, but I wonder if it's needed? I'm not quite sure what the use case of moving between book detail views within one category is.

**Comment by johnfactotum** [comment]
A question: does this mean that it would no longer support opening multiple books at a time? Otherwise one could end up with multiple instances of the library view. But the ability to open multiple books (or even multiple instances of the same book) at the same time is quite important, especially for reading technical materials, or other nonfiction books, and I would hate to lose that ability.

**Comment by bertob** [comment]
Is having multiple instances of the library open at the same time a problem? If that's a concern I think there are ways to avoid it, e.g. having an explicit "open in separate window" action on books in the library.

**Comment by johnfactotum** [comment]
OPDS support is still WIP in the gtk4 branch, but it does have everything in a single window now.
![image](https://github.com/johnfactotum/foliate/assets/50942278/5931b575-81aa-470e-8b92-641211d9fa1d)
![image](https://github.com/johnfactotum/foliate/assets/50942278/9b37d4fc-5fc2-47d2-9284-d50617f0eedd)
