### ISSUE TITLE
Accelerate Preparing book first read

### ISSUE THREAD

**Issue by francoisbillard** [johnfactotum/foliate#526]
The preparing book first read can take several seconds, it can be boring when opening hundreds of ebook to class them for example. 
Foliate could load quickly a first chunk of data to display it immediately and preparing the remaining data asynchronously.

Nice job guy
Regards

**Comment by johnfactotum** [comment]
To get the correct chapter title, the whole book is in fact loaded and parsed (but not rendered) before the book is shown, which is why opening some books in Foliate 2.x is a lot slower than 1.x. To fix this it should behave more like the generated locations (don't prevent the book from displaying, and cache the result).

**Comment by johnfactotum** [comment]
In the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch, it now only loads the one chapter that it's displaying, and nothing else. So everything is now much faster.
