### ISSUE TITLE
How difficult would it be to create a macOS build?

### ISSUE THREAD

**Issue by SquareBottle** [johnfactotum/foliate#535]
**Question:**
I've been lamenting the surprising lack of good ebook readers for a while – my roommate can vouch for that – and what you've made looks _fantastic_. I see that you've made versions for lots of linux and BSD distros, and that makes me wonder: how tricky would it be to make a build for macOS? I know that sometimes it's wildly difficult because of Apple being Apple, sometimes it's something easy that doesn't happen until somebody asks, and sometimes the developer doesn't know because they don't have experience making stuff for macOS. I'm wondering what the case is here. Not looking for a commitment or anything.

Regardless of the answer, thank you very much for making Foliate!

**Version:**
 - Foliate version: Any, ever.
 - OS/Distribution and version: macOS 10.15.5 or future
 - Desktop environment: Aqua
 - Installation method: Hopes and dreams

**Comment by bbblanccc** [comment]
Please refer to this issue #300
The biggest problem of cross-platform build is finding stable `WebKitGTK` and `gjs` native to MacOS or Windows. `gjs` is in macports but `WebKitGTK` no. So macOS build may not be available quickly.

**Comment by johnfactotum** [comment]
Sorry, closed the wrong issue.

**Comment by SalahAdDin** [comment]
@johnfactotum Is it on your plans now?

**Comment by johnfactotum** [comment]
I don't really have any plans for this for the foreseeable future. Personally, I would rather see a native app for macOS, rather than building Foliate on it, as it's a relatively simple app, and an app built with the native toolkit would integrate better.

It should be possible for people to build it themselves, though, as long as you can get [GJS](https://ports.macports.org/port/gjs/) and [WebKitGTK](https://ports.macports.org/port/webkit2-gtk/) to build.
