### ISSUE TITLE
Please give an option to change layout to 'strictly' Two Columns

### ISSUE THREAD

**Issue by theVentus** [johnfactotum/foliate#538]
I'm in awe with this app. But one thing which is bugging me is that in automatic layout settings, the epub would just go on showing 4 columns when width is increased, ruining the reading experience. But if we try to keep it in 2 columns, the width would be too little and a significant portion of screen space goes unused. It'd be great if like a Single column option, you can implement Two Column one, which stays in 2 columns even after width gets increased above 1500.

**Comment by master-of-zen** [comment]
@theVentus current fix for me is to increase zoom until it switches to two columns

**Comment by apandada1** [comment]
@johnfactotum  This was fixed in the master branch (with the "upto two column mode"), but after today's update (v2.6.0), the "upto two column mode" is missing, and it shows four columns in high resolution displays in "automatic" mode.

![Screenshot from 2021-03-24 11-19-49](https://user-images.githubusercontent.com/3063132/112262201-47f12800-8c93-11eb-96b5-265ea595fd4e.png)

**Comment by johnfactotum** [comment]
Yeah, my bad. Should be fixed in 2.6.1.
