### ISSUE TITLE
The app is not working in linux mint 19.3 + cinnamon

### ISSUE THREAD

**Issue by d4g0** [johnfactotum/foliate#541]
**Tthe bug**
The app fails to open, when i try to useit i see the icon in the panel and the dock but affter a few seconds it desapears.
Also im unable to see the process in the system monitor

**Steps to reproduce**
1. Use a Linux Mint OS 
2. Instal Foliate
3. Open it

**Expected behavior**
I will spect to be able to use the app.

**Version:**
 - Foliate version: 2.4.2 , 2.3.0
 - OS/Distribution and version: Linux Mint 19.3
 - Desktop environment: Cinnamon
 - Installation method: PPA for Ubuntu 18.4 , 19.10  and Release page source .deb downloads

**Comment by stevenpusser** [comment]
Have you tried starting it from the terminal?

**Comment by apandada1** [comment]
I can confirm this issue in Linux Mint 19.3 Cinnamon from the PPA and the .deb file in the releases page. However, this bug is absent in KDE Neon (tried ppa version) running in the same machine and Manjaro Cinnamon (tried Pacman version) running in another machine.

* When I double click on the epub, Foliate does not open.
* When I run `com.github.johnfactotum.Foliate path/to/book.epub ` there is no output, and Foliate does not open. I am presented with a new prompt.
That is,when I enter the first line, there is no output, and I get the second line
```
name@mypc:~$ com.github.johnfactotum.Foliate path/to/book.epub
name@mypc:~$
```
* When I run with `sudo com.github.johnfactotum.Foliate path/to/book.epub` I get the following output, and it is stuck there. No window opens.

```bash
(com.github.johnfactotum.Foliate:20249): Gjs-WARNING **: 14:28:45.659: JS ERROR: Error: No property allow_top_navigation_to_data_urls on this GObject WebKitSettings
_init@resource:///com/github/johnfactotum/Foliate/js/epubView.js:568:32
_init@resource:///com/github/johnfactotum/Foliate/js/window.js:889:22
main/</<@resource:///com/github/johnfactotum/Foliate/js/main.js:310:29
main/<@resource:///com/github/johnfactotum/Foliate/js/main.js:304:16
main@resource:///com/github/johnfactotum/Foliate/js/main.js:474:12
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/usr/bin/com.github.johnfactotum.Foliate:9:1
```

* When I open Foliate first (the window loads when there is any book) and select the book in `Open File`, the window closes. When run from the Terminal, the window opens. Select a book (open file), and the window closes. There is no output in the Terminal.

System monitor shows that Foliate is running in the background (even after the window closed, and the Terminal went to a new prompt). It just does not show up and it's not minimized either.

The book I tried to open is [this](https://standardebooks.org/ebooks/jules-verne/twenty-thousand-leagues-under-the-seas/f-p-walter). However, Foliate cannot open any other epub files in Linux Mint, and the same books works perfectly with Foliate (in the same machine) in KDE Neon.

**Comment by johnfactotum** [comment]
Does Linux Mint have GJS? I thought they only have CJS.

**Comment by apandada1** [comment]
GJS would be installed as a dependency when Foliate is installed. I don't know whether GJS is installed by default in Cinnamon.

**Comment by apandada1** [comment]
I can confirm that this bug is absent from Linux Mint 20 Cinnamon Edition. I used the latest version (2.4.2) from the stable PPA.

**Comment by d4g0** [comment]
Well since the problem gets solve doing what all we most do (upgrade our OS) i will be closing the issue.
