### ISSUE TITLE
Replace close window icon in sidebar annotations with trash bin icon

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/foliate#563]
I think it would look better to use the trash bin icon from the popover dialogue to indicate when removing annotations from within the sidebar. Would this be possible? At least it would look more consistent in conjunction with the popover aesthetics and more likely prevent users from accidentally removing annotations.

**Comment by johnfactotum** [comment]
The icon is actually `edit-delete`, which, according to the [specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), is "The icon for the delete action."

In many icon themes (like Yaru, elementary, and Paper), it is actually rendered as a trash bin. Other themes (like Arc) would show a "minus" icon. It just so happens that in Adwaita, they decided to make it look like an X.

The `edit-delete` icon is semantically more correct than the trash bin, and in the sidebar there's less risk of mistaking it for "close". The trash bin used in the annotation popover is a workaround, since the risk of mistaking is very high there. Another option would be to use the `list-remove` icon; but this again can't be used in the annotation popover, as there's no list there, just a single annotation.

**Comment by johnfactotum** [comment]
In the `gtk4` branch, it doesn't have buttons anymore for annotations in the sidebar, as I feel that the space is a bit tight now that annotations are shown in a tree, and the color/style indicator is wider than before.

But it does use the trash bin icon for bookmarks now. So I think this can be closed.
