### ISSUE TITLE
Bottom rounded corners

### ISSUE THREAD

**Issue by YaLTeR** [johnfactotum/foliate#612]
I think rounded corners at the bottom would make the window look better, especially when the controls and the header bar are hidden. This is also slowly becoming the standard GNOME application window shape.

In GTK 3 bottom corners are automatically rounded when using `HdyApplicationWindow` instead of `GtkApplicationWindow`, and GTK 4 can do them natively with CSS.

**Comment by johnfactotum** [comment]
I plan to do this when porting to GTK 4.

The reason is that `HdyWindow` requires packing the header bar inside the window (rather than in the title area). It feels like a rather cumbersome change, particularly when we currently also have to support the case where `libhandy` is not installed.

Using `HdyWindow` would also enable some more fundamental changes:
- In scrolled or continuous layouts, the header bar will be able to be overlaid on top of the content, making auto-hide work better for these layouts.
- In skeuomorphic mode the header bar can possibly be moved inside (or overlaid on top) the book-like shadows, which will make auto-hiding header bar possible when skeuomorphic mode is enabled.

These require  some restructuring, which (a) I don't have time for right now, (b) would possibly need to be redone when porting to GTK 4. So I've decided to wait for GTK 4 for now.

**Comment by Kekun** [comment]
You don't have to handle the case where libhandy isn't installed: just declare you depend on it, all relevant distros ship it since quite some time, and in the *worst* case you can include it as a submodule like many app did for some time.

**Comment by MichalLebeda** [comment]
Sorry for stupid question, but GTK4 is meant to have all four corners rounded? I really like that look so it is not a problem, but I thought that it is currently just a workaround for puting title bar inside content area.

**Comment by YaLTeR** [comment]
> Sorry for stupid question, but GTK4 is meant to have all four corners rounded?

Yes, or at least it was before it was reverted due to [this issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3432). Idk if it'll get fixed (and rounded corners by default re-introduced) before release.

**Comment by johnfactotum** [comment]
Let's just track this with #716.
