### ISSUE TITLE
undefined is not an object (evaluating 'zip.file(/\.fb2$/)[0].async')

### ISSUE THREAD

**Issue by YaLTeR** [johnfactotum/foliate#629]
**Describe the bug**

Upon opening [Бодрийяр_-_Общество_потребления.fb2.zip](https://github.com/johnfactotum/foliate/files/5572506/_-_._.fb2.zip):

![image](https://user-images.githubusercontent.com/1794388/99782516-50d9bd80-2b2a-11eb-9b80-716cd67a58c2.png)

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Fedora 33
 - Desktop environment: GNOME 3.38
 - Installation method: Flatpak

**Comment by itprojects** [comment]
The book has a garbled filename (`KOI8-R`?), but the book opens fine, once first unzipped to get to the `.fb2` file. Book fonts appear as Russian, so if you can read Russian then "no real bug". This bug is in fact hyper-real.

**Comment by YaLTeR** [comment]
Yeah, I noticed that after manual extraction it opens fine. The bug is then that it doesn't open fine without having to manually unzip it and shows a cryptic error.

**Comment by johnfactotum** [comment]
The error means `zip.file(/\.fb2$/)` is undefined, meaning there's no file matching `*.fb2` in the zip file. And this happens because the file name is not encoded in UTF-8, so when decoded as UTF-8, the file name does not end in `.fb2`.

According to [JSZip documentation](https://stuk.github.io/jszip/documentation/api_jszip/load_async.html):

> A zip file has a flag to say if the filename and comment are encoded with UTF-8. If it’s not set, JSZip has **no way** to know the encoding used.

I suppose, instead of finding the file machting `*.fb2`, we could just open the first file contained in the zip. After all, we're already told by GLib that it's a zipped fb2 file, so we should be fairly confident that this would work.
