### ISSUE TITLE
Add option to have fixed-layout ebooks fill the window.

### ISSUE THREAD

**Issue by rkjnsn** [johnfactotum/foliate#633]
**Is your feature request related to a problem? Please describe.**
Different fixed-layout epubs have different viewport sizes, and thus render at different sizes when Foliate is set to 100% zoom. It can be annoying to have to play with the zoom for each book to find the sweet spot to fill the maximum amount of the screen, without causing the left-hand page to pull away from the spine. Even so, there's still a gap at the bottom. 

**Describe the solution you'd like**
Most e-reading apps that support fixed-layout epubs will automatically size the content to fit the window, switching between a single page and two side-by-side depending on the aspect ratio of the screen / window.

It would be nice if Foliate did the same by default, or at least had an option to fill the screen.

**Comment by johnfactotum** [comment]
> It can be annoying to have to play with the zoom for each book to find the sweet spot to fill the maximum amount of the screen, without causing the left-hand page to pull away from the spine.

See #161. It's already fixed when we upgraded to Epub.js 0.3.86 (7315fe90be6ae1271e99ef94b20211a4b13b1f5c). I think the book needs to specify the `page-spread-left` or `page-spread-right` properties for the spread to be joined properly.

> Even so, there's still a gap at the bottom.

If you're talking about the footer/navbar, see #230.

> Most e-reading apps that support fixed-layout epubs will automatically size the content to fit the window, switching between a single page and two side-by-side depending on the aspect ratio of the screen / window.

I think it already does that by default.

**Comment by rkjnsn** [comment]
I'm using Foliate 2.5.0, which looks like it includes that revision.

Here's some screenshots to clarify the issue:

This is at the default 100% zoom level. The pages only fill part of the available height:
![100% Zoom](https://user-images.githubusercontent.com/7364197/101208446-0e82a700-3627-11eb-9131-4d694c55bb8c.png)

Zooming in to 150%, the pages fill *most* of the page, but don't *quite* reach the footer at the bottom:
![150% Zoom](https://user-images.githubusercontent.com/7364197/101208724-70431100-3627-11eb-8708-9533110366ba.png)

However, if I zoom in any more, the left-hand page pulls away from the spine, leaving a gap:
![160% Zoom](https://user-images.githubusercontent.com/7364197/101208841-9e285580-3627-11eb-8ab6-2a9037e35227.png)

**Comment by johnfactotum** [comment]
It doesn't fill the window because the width is capped at 1400px (the "Width" option in the primary menu). If you increase the width to something wider than your screen, and also set "Margins" to 0, then it should fill the window completely (apart from the footer).

I suppose one needs to do something to make the max-width and margin options more obvious and less confusing (ever since that setting was implemented (see #192) there has been some reports on how they were unable to make the page fill the window). All the layout options, really, probably needs some reorganizing and consolidating.

> the left-hand page pulls away from the spine, leaving a gap

As I mentioned above, currently the book needs to set `page-spread-left` or `page-spread-right` for the spread to be joined properly. The gap doesn't appear, for example, with the [*Page Blanche*](https://github.com/IDPF/epub3-samples/releases/download/20170606/page-blanche.epub) sample from [EPUB 3 Samples](https://idpf.github.io/epub3-samples/30/samples.html). I guess this is still an Epub.js bug, because even if they aren't specified to be a right or left page, they should still be joined together. Then again, I'm not really an expert on fixed layout books...

**Comment by rkjnsn** [comment]
Ah, I didn't realize that was setting the maximum width for rendering. Increasing it does allow the page to fill the window. Thanks!

I originally thought that the spine was being properly joined, and was separating at "to-high" zoom levels due to a separate bug. Now I see that it only appeared to be joined at lower zoom levels due to the width constraint. I double checked, and while many of my fixed-layout books have `page-spread-left` and `page-spread-right`, the two I happened to test with did not. Oops. Never the less, every other ereader I've tried does join the spine on these books, so Epub.js presumably should as well, but as you say, that's an Epub.js bug.

Sorry for the misdiagnosis on my end.

**Comment by rkjnsn** [comment]
Should I file an Epub.js bug for this? It seems a lot of fixed-layout epubs omit `page-spread-left` and `page-spread-right` but expect the spine to be joined. Even when they don't need to be joined for content reasons, putting both fixed-layout pages on the left edge of their respective columns looks odd and unbalanced:

![The Eye of the World](https://user-images.githubusercontent.com/7364197/113522026-5c1a0c80-9552-11eb-846c-c311b4af853f.png)

Even if not joined, I would would expect both pages to be rendered equidistant from the center line.

**Comment by johnfactotum** [comment]
I guess this should be closed, and #161 reopened, because the issue here is that the pages should be joined.
