### ISSUE TITLE
Error when trying to open EPUB book

### ISSUE THREAD

**Issue by ghost** [johnfactotum/foliate#639]
When trying to open an e-book with the EPUB format, I get this error. I am using Foliate 2.5.0 on Debian Buster with Gnome desktop. The book opens in calibre without issues. See attached screenshot.
![Skärmbild från 2020-12-10 07-50-30](https://user-images.githubusercontent.com/23194385/101732102-926be180-3ab4-11eb-84d1-4ebb7636bc2d.png)

**Comment by johnfactotum** [comment]
It looks like the EPUB is missing `/meta-inf/container.xml`, which is required.

**Comment by jony0008** [comment]
But why can it be opened by other readers without any problems?

**Comment by johnfactotum** [comment]
Maybe they fall back to a fixed OPF path, or try to find whatever OPF file that exists in the zip file.

Maybe there _is_ a `container.xml`, but Epub.js just can't find it because of encoding problems or other bugs in JSZip. So other programs might not have this problem.

Or maybe it isn't even a real EPUB file at all. So it fails when opened as an EPUB, but other readers might open it as the correct format and succeeds.

It's really not possible to tell without examining the file.
