### ISSUE TITLE
MIME types seem to be set up wrong after installing from Flathub

### ISSUE THREAD

**Issue by Elijahrane** [johnfactotum/foliate#646]
**Describe the bug**
After installing from Flathub, the DE (in my case MATE) seems to think that Foliate can open all text files. 

**To Reproduce**
1. Install foliate from flathub
2. Open your DE's file manager.
3. Notice how it sees Foliate as valid to open any file that could be opened by a normal text editor, and (very annoyingly) may even prefer it.

**Expected behavior**
Foliate should give the DE an accurate list of file types it can actually read.
![foliatebug2](https://user-images.githubusercontent.com/60792108/102702702-78928180-42a0-11eb-90db-3047fb292318.png)
![foliatebug1](https://user-images.githubusercontent.com/60792108/102702704-79c3ae80-42a0-11eb-8e43-b5ca6b67a3c0.png)

**Screenshots**

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Solus
 - Desktop environment: MATE
 - Installation method: Flatpak

**Comment by johnfactotum** [comment]
Foliate can open JSON files as [Web Publication Manifest](https://github.com/readium/webpub-manifest) files, and XML files as [Open Packaging Format (OPF)](http://idpf.org/epub/20/spec/OPF_2.0.1_draft.htm) files, so technically it's not wrong to say that it can handle JSON and XML files (at least to some degree).

I guess we should remove them from the desktop file, since it's not really useful for most users and will only cause confusion.
