### ISSUE TITLE
Foliate doesn't open in fedora 28

### ISSUE THREAD

**Issue by lmpeiris** [johnfactotum/foliate#648]
**Describe the bug**
Foliate manages to compile properly on fedora 28. Gnome 3 gets the icon for launching as well. However when either clicking icon from gnome 3, select Foliate to open a pdf does not do anything. There are no processes spawned when i check.

However, when running below it gives error:

```
[lmpeiris@lmpdesktop5 foliate-2.5.0]$ which com.github.johnfactotum.Foliate 
/usr/bin/com.github.johnfactotum.Foliate
[lmpeiris@lmpdesktop5 foliate-2.5.0]$ com.github.johnfactotum.Foliate

(com.github.johnfactotum.Foliate:8428): Gjs-WARNING **: 12:16:50.231: JS ERROR: TypeError: webContext.set_sandbox_enabled is not a function
@resource:///com/github/johnfactotum/Foliate/js/main.js:38:1
@/usr/bin/com.github.johnfactotum.Foliate:9:1

Script /usr/bin/com.github.johnfactotum.Foliate threw an exception
```

**To Reproduce**
1. download and compile using standard compiling method
2. Run foliate by clicking on icon

**Expected behavior**
Foliate should load

**Screenshots**
none. However see the attached text file for commands which were run and compiler output.

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: fedora 28
 - Desktop environment: 3.28
 - Installation method: compiling from source.
 -  Meson: 0.47.2
 -  Ninja: 1.8.2
 -  webkit2gtk3: 2.24.1
 -  gjs: 1.52.5
 -  gettext: 0.19.8.1

**Additional context**
Please see attached text `file`

**Comment by lmpeiris** [comment]
[foliate_compile_log.txt](https://github.com/johnfactotum/foliate/files/5738524/foliate_compile_log.txt)

**Comment by johnfactotum** [comment]
> select Foliate to open a pdf does not do anything

It doesn't support PDF.

> However, when running below it gives error

This error would seem to have occurred because you're using WebKitGTK 2.24, which does not support [sandbox](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-set-sandbox-enabled), which is only available in versions >= 2.26.

As a workaround, you may try deleting this line from `main.js`

https://github.com/johnfactotum/foliate/blob/c570ba1b03d5188aa335a485784b121f430ebcd1/src/main.js#L38

However I would not recommend this. Running an outdated version of WebKit is not secure, and is not supported by Foliate. You should consider upgrading to a newer, supported version of Fedora.

**Comment by itprojects** [comment]
Foliate [2.5] works on Fedora 28 with the official flatpak, [repository here.](https://flathub.org/apps/details/com.github.johnfactotum.Foliate)

You can open a book from Nautilus.

**Comment by johnfactotum** [comment]
Closing this as it's not really a bug; Foliate requires an up-to-date version of WebKit.
