### ISSUE TITLE
Jagged font rendering

### ISSUE THREAD

**Issue by poperigby** [johnfactotum/foliate#650]
**Describe the bug**
Text has jagged edges that makes it look like there isn't anti-aliasing.

**To Reproduce**
1. Open any .epub file in Foliate

**Expected behavior**
The font is rendered with smooth edges.

**Screenshots**
![image](https://user-images.githubusercontent.com/20866468/103426646-e4fa6400-4b6f-11eb-8252-b6daa884a2f2.png)
![image](https://user-images.githubusercontent.com/20866468/103426669-00656f00-4b70-11eb-880d-af32fd73e935.png)

**Version:**
 - Foliate version: 2.5.0
 - OS/Distribution and version: Arch Linux
 - Desktop environment: SwayWM
 - Installation method: Official Arch Linux repository

**Comment by johnfactotum** [comment]
Does this happen with Epiphany or other WebKitGTK apps?

**Comment by FreeFull** [comment]
It seems that the jagged fonts happen with the Wayland GDK backend, but not with the X11 backend.

**Comment by PopeRigby** [comment]
> Does this happen with Epiphany or other WebKitGTK apps?

Yeah.

> It seems that the jagged fonts happen with the Wayland GDK backend, but not with the X11 backend.

Yep, that seems to be the case. Running `GDK_BACKEND=x11 foliate` doesn't produce the problem.

**Comment by zlandau** [comment]
For what it's worth, you can put the override within the .desktop file. For example:

```
$ tail -n1 .local/share/applications/com.github.johnfactotum.Foliate.desktop
Exec=env GDK_BACKEND=x11 com.github.johnfactotum.Foliate --library
```

**Comment by louwers** [comment]
> > Does this happen with Epiphany or other WebKitGTK apps?
> 
> Yeah.
> 
> > It seems that the jagged fonts happen with the Wayland GDK backend, but not with the X11 backend.
> 
> Yep, that seems to be the case. Running `GDK_BACKEND=x11 foliate` doesn't produce the problem.

It does for me.

![image](https://user-images.githubusercontent.com/649392/115303569-140b0480-a164-11eb-9bb5-ce7f4277d847.png)

Running GNOME + Wayland.

**Comment by johnfactotum** [comment]
Closing as it's not fixable in Foliate and not actionable.

**Comment by ducky-fish** [comment]
On the GDK_BACKEND solution not working for me I uninstalled the snap edition and downloaded the .deb from the Foliate github. This solved my rendering issues. 

Commenting for those who may encounter a similar issue in the future.

**Comment by denisftw** [comment]
The font issues are so simple and yet, there's so little understanding among most people including the vast majority of developers. So, leaving it here for @johnfactotum and everyone who stumbles upon this.

The first message complains about jagged fonts and says that it "makes it look like there isn't anti-aliasing". There is indeed no anti-aliasing in the screenshot, but jagged fonts have nothing to do with it. The fact of the matter is that @poperigby has anti-aliasing disabled either system-wide or framework-wide either intentionally or unintentionally. If it's disabled, then no application should ever try to override this setting, otherwise it would belong to the rubbish bin, so there's no problem here.

Now, if you enable AA, then you'll still have jagged fonts, but because of the blur introduced by AA, you will not see it. Common sense suggests that looking at blurry text all day long will not be good your eyesight in the long run, but apparently nobody cares. That's why these bugs are so obscure: most developers and QA engineers have AA enabled and they simply cannot see it.

OK, so what do we see in the screenshot? Actually, what we see is a problem with _hinting_. It's so happened that the characters currently running the GNOME project, specifically those in charge of `cairo`, had made the decision to change their approach to hinting in GTK4. You can find a couple of heated threads on GNOME GitLab, but the gist is this: "We decided to change it, if you don't like it, use something else". Currently, there aren't that many apps that already switched to GTK4, so many users with disabled AA don't yet see this problem. And everyone else who have AA enabled will never see it (this is not entirely true: some people might detect bad hinting even with AA enabled but those are very rare).

Essentially, what it means is that GTK4 makes AA blur necessary to hide font imperfections, so any app that uses GTK4 will force the user to either enable AA or uninstall the app. If the user had a strong reason not to enable AA before, it will probably be the latter.

**Comment by johnfactotum** [comment]
These screenshots are from the GTK 3 version.

**Comment by filmor** [comment]
Also, I remember seeing the jagged fonts in Flatpak but not on the "native" system. So there's that. The changes in GTK4 are mostly about sub-pixel stuff, which is considered outdated with current high DPI screens.

**Comment by Sunspark-007** [comment]
I have a custom fontconfig folder and fonts.conf in it that I use with the Firefox flatpak to set the rendering nicely for me, no AA, correct hinting, etc.

I copied it over to foliate's flatpak config folder on KDE and checked it out.. but curiously, it only affects the app interface itself.. but not the ebook content itself which remains AA.

What am I missing here that the ebook text doesn't pick up the custom settings from the fonts.conf when Firefox does?

On QT when this happens it's usually because of an issue with a QT widget that forces AA, but Foliate is a GTK app..

**Comment by johnfactotum** [comment]
WebKitGTK handles font rendering differently and is known to be buggy. See #1227.
