### ISSUE TITLE
Font styling not working properly when custom font is set

### ISSUE THREAD

**Issue by monday15** [johnfactotum/foliate#67]
Thank you very much for providing such a great app!

There is a bug, it appears in several books - when custom font is set, headers uses normal font-weight instead of bold (switching to publisher font fixes the issue).
Example book can be downloaded here: https://www.planetebook.com/the-odyssey/
Right at the start of the book, header 'The Odyssey By Homer (Circa 700 BC)  Translated by Samuel Butler' is bold with publisher fonts, but normal with custom font.

Note, in some other books, I've also seen text hunks (like few words at the start of paragraph or a quote) styled with bold/italic, and they were rendered correctly. Issue only appears on headers.

**Comment by johnfactotum** [comment]
Actually it's not only the weight that's broken with this book. The headings should also be bigger.

Why does it break? Because the "headings" in this book are not real headings, but actaully paragraphs (`<p>`s) with different classes. One could try to avoid styling `<p>`s with additional classes, but that will also break some books. The problem is that we have no way of knowing whether a style was added to set something useful, or if it's just hardcoding stuff for no good reason.

For example:
- **Case 1:** a book may have a `.no-indent` class on the first paragraph, so the first paragraph will have no indent, but the stylesheet somehow also specifies a font-size. This makes no sense, because it should have the same size as other paragraphs. So we want to override the size in this case.
- **Case 2:** But the same book may have a `.chapter-title` class, and the stylesheet says that paragraphs with this class should be big and bold. In this case, we don't want to override.

The problem is that we don't know if we're dealing with case 1 or case 2. So the compromise is to try to force font-size and weight on *all* paragraphs (`<p>`s).

I suppose one might want to be less aggressive with font-weights. But if we do that, then the user will no longer be able to adjust the font-weight if a book somehow hardcodes `font-weight: normal;` or something on all of its paragraphs.

**Comment by monday15** [comment]
Well, I've tried to ignore that, but reading process is kinda uncomfortable without bold headers. 

Please, consider adding an option to force/ignore font-weights in the book. Since it is not a common issue, probably, a good idea will be to hide the option somewhere in "Additional Options" dialog to not overwhelm current ui (or even make it accessible only with dconf - `gsetting set ...` or using dconf-editor).

**Comment by johnfactotum** [comment]
Yes, the viewing options popover is getting more and more crowded. But now that I've added a preference window, I guess I can add more granular controls there.

**Comment by johnfactotum** [comment]
I've decided to use less aggressive override for font-weight for now, since that's also what's currently done with font-style.

**Comment by monday15** [comment]
Great! Thanks!

Works fine, headers are bold.
