### ISSUE TITLE
your site page to the .deb file is broken

### ISSUE THREAD

**Issue by mkrier** [johnfactotum/foliate#676]
I just went to https://johnfactotum.github.io/foliate/ and clicked on 

Ubuntu (.deb) | Download

and it leads here: https://github.com/johnfactotum/foliate/releases/tag/2.5.0

Soooooo how do I download the .deb file?

**Comment by itprojects** [comment]
@mkrier It seems the version 2.5 tag is missing the `.deb` files. You can try using [Ubuntu's](https://launchpad.net/~apandada1/+archive/ubuntu/foliate/+packages).

**Comment by apandada1** [comment]
@mkrier Here is the exact download link of the .deb file from the Launchpad PPA https://launchpad.net/~apandada1/+archive/ubuntu/foliate/+files/foliate_2.5.0-ppa1_all.deb

**Comment by johnfactotum** [comment]
Ah, yes, I forgot to build the .deb for 2.5.0.

Although, seeing that no one complained after 5 months since its release makes me wonder if it's really needed at all.

**Comment by itprojects** [comment]
@johnfactotum Since you have the Ubuntu `.deb`, from @apandada1, you could change the table to

Ubuntu (PPA)
or Debian

then you don't need the line
> Debian packages can be downloaded from the releases page.

If the `.deb` does not work for Debian users, they always have the `.flatpak`!

Or even better:

Message to **any** _Debian_ package maintainer reading this comment, please pick up the app, it's well worth it!

**Comment by apandada1** [comment]
> If the .deb does not work for Debian users, they always have the .flatpak!

I have manually downloaded and used the .deb from the PPA in Raspbian, it should work on Debian too.
> please pick up the app

There have been [some progress](https://github.com/johnfactotum/foliate/issues/530#issuecomment-678782492). @okias Once told me that for it to be included into Debian, the app should not have any minimized js libraries, and it should rather compile the source js libs into the minimized files during building.

**Comment by itprojects** [comment]
@apandada1 In you personal estimation, how many Debian users will use the `.flatpak` vs the `.deb` (of Debian)?

Also do you use any Snap apps, with Debian?

**Comment by apandada1** [comment]
> @apandada1 In you personal estimation, how many Debian users will use the .flatpak vs the .deb (of Debian)?

I really have no idea about relative download counts. AFAIK, snap/flatpak download counts are probably not public. 
I use Debian only on a Raspberry Pi (did not try snap/flatpak).

According to [ppa stats](https://github.com/YokoZar/ppa-stats), v2.5.0  has been downloaded (through apt, not counting direct downloads from Launchpad) 5224 times.

```
$ ppa-stats -a amd64 apandada1/foliate
foliate 2.5.0-ppa1 hirsute amd64 5254
```
(the same package has been copied across all supported versions of Ubuntu, that's why is shows the same number for other Ubuntu versions. I know that ppa-stats is quite accurate because I have checked it for my less used ppa's which I have myself downloaded 3-4 times to test, and ppa-stats showed it accurately).

**Comment by itprojects** [comment]
Thanks for the info.

**Comment by mh182** [comment]
> Ah, yes, I forgot to build the .deb for 2.5.0.
> 
> Although, seeing that no one complained after 5 months since its release makes me wonder if it's really needed at all.
I found Foliate when I was "forced" to use Ubuntu (using snap installation). But since I use Debian on all my other machines I would really appreciate having a Debian package for it.

Thanks for the great work with Foliate - IMHO the best standalone ebook reader on Linux ATM.

As for if it is worth - I prefer Debian packages because I know that packaging an application as Debian package implies going  through a vetted process (ie. a Debian Developer). It is easier to trust a known process than some "random-dude with a github account" ;-) 
Not having a Debian package = one more hurdle to reach my machine. It probably makes integration of the software easier for Debian derived Linux distributions.

**Comment by svoboda77** [comment]
Since version 2.6.1 is out, will you please also release deb packages for Debian? Thank you.

**Comment by johnfactotum** [comment]
Done: https://github.com/johnfactotum/foliate/releases/download/2.6.1/com.github.johnfactotum.foliate_2.6.1_all.deb

**Comment by svoboda77** [comment]
Thank you :) 👍
