### ISSUE TITLE
Two page book view for any window size

### ISSUE THREAD

**Issue by maxborowsky** [johnfactotum/foliate#682]
Please, if the development is still ongoing and the project is not dead - add the ability to fix a two page view (not three columns, not four, no forced view like old newspapers and magazines :-) ). I know this has been asked many times already, but please _prioritize_ adding this feature. (I really don't want to install heavy and monstrous Calibre just for the sake of the built-in E-book viewer...)

And it would be logical, in addition to manually selecting the maximum page width, to offer the ability to simply specify 100%, and also make the margin value affect not the margin from the edge of the _window_, but for the edges of the _page_.

**Comment by johnfactotum** [comment]
Thanks for the suggestion, and sorry for any inconvenience caused by not having this feature.

The main reason I haven't got around fixing this (apart from lack of time to work on this project) is that it involves patching Epub.js. The current way it's patched is already hacky and clearly not sustainable, so I just don't want to make that situation even worse. Having margins inside the page is also not something that's supported out-of-the-box by Epub.js. And the overall layout options definitely needs some reorganizing.

Still, I suppose there's clearly enough demand for this specific issue to warrant a hacky solution. So I guess I'll try to make one as soon as possible.

**Comment by itprojects** [comment]
@maxborowsky Here is the original discussion. https://github.com/johnfactotum/foliate/issues/257

**Comment by itprojects** [comment]
The `epub.js` developer made interesting commentary.

Looking at futurepress/epub.js/issues/525

>  I'd certainly accept a PR adding the options to set multiple columns

Yours PR/MR? Two great projects may benefit massively. No more "hacky".

>  but I'm not likely to implement it any time soon.

If you, @johnfactotum , still have some time...

**Comment by maxborowsky** [comment]
@johnfactotum, thanks for your great work and for not forgetting the dinosaurs who read books not only on ipads and kindles, but also on the old good desktops :-)

**Comment by itprojects** [comment]
> thanks for your great work and for not forgetting the dinosaurs who read books not only on ipads and kindles

+1

**Comment by johnfactotum** [comment]
So I ended up implementing the proper solution. Not only is there now an "up to two columns" layout, the "automatic" layout now also supports up to an infinite number of columns, not just 4 columns.

**Comment by johnfactotum** [comment]
@marsoochan You can use the "Single Column", "Scrolled", or "Continuous" layouts.
