### ISSUE TITLE
Is Ubuntu PPA packages compatible with Debian 10/Buster?

### ISSUE THREAD

**Issue by calibs** [johnfactotum/foliate#685]

**Comment by apandada1** [comment]
I have used it in Raspbian Buster, and it works perfectly.

The PPA does not host any dependencies (it only hosts the package Foliate), and in principle it should not break anything, but adding a PPA to Debian is discouraged.

Instead of adding the PPA to sources.list, you can download the [.deb file](https://launchpad.net/~apandada1/+archive/ubuntu/foliate/+files/foliate_2.5.0-ppa1_all.deb) from the PPA, and install manually with gdebi or with `sudo apt install ./path/to/package.deb`. That certainly won't break the system.

**Comment by calibs** [comment]
> I have used it in Raspbian Buster, and it works perfectly.
> 
> The PPA does not host any dependencies (it only hosts the package Foliate), and in principle it should not break anything, but adding a PPA to Debian is discouraged.
> 
> Instead of adding the PPA to sources.list, you can download the [.deb file](https://launchpad.net/~apandada1/+archive/ubuntu/foliate/+files/foliate_2.5.0-ppa1_all.deb) from the PPA, and install manually with gdebi or with `sudo apt install ./path/to/package.deb`. That certainly won't break the system.

Thanks for the advice!
