### ISSUE TITLE
Using Foliate in Android phone with Termux

### ISSUE THREAD

**Issue by apandada1** [johnfactotum/foliate#690]
I installed Ubuntu 20.04 (as proot) in Termux in an Android phone, and I can access the XFCE desktop with VNC (I used [Andronix](https://andronix.app/)). Then I installed Foliate (from the PPA).

Foliate runs, but I first encountered [this issue](https://github.com/johnfactotum/foliate/issues/668) when I tried to open a book, and I used the workaround  `sudo chmod u+s /usr/bin/bwrap` (it seems that this issue pops up on older kernels, e.g. kernel 4.9 in my Android phone).

However, now I get this error message in terminal, when I try to open a book (the window opens, but the book keeps loading forever)
```
bwrap: Can't read /proc/sys/kernel/overflowuid: Permission denied
```
This may be due to restrictions in recent Android versions (I have Android 10), as reported here https://github.com/termux/termux-app/issues/299

I don't know if Foliate necessarily needs to make such kernel level calls in order to open books. Is there any way to bypass it by slightly modifying the code?
There is such a fix for libreoffice https://github.com/EXALAB/AnLinux-App/issues/24#issuecomment-543143007

If this can be done, then Foliate could be conveniently used to read books in Android tablets/phones with large screens.

**Comment by apandada1** [comment]
I found that `WEBKIT_FORCE_SANDBOX=0 com.githhub.johnfactotum.foliate` successfully loads the books!!!
So far I was using a VNC viewer in my computer.

I would now check it works with touch screen in phone's VNC viewer, and I would also post a step by step guide (so please don't close the issue right now).

**Comment by archisman-panigrahi** [comment]
Here is how to install Foliate in an Android device **without rooting**
-------------------------------------------------------------------------------------------------------------

1. Install [Termux](https://termux.com/) from F-Droid or Play Store (Google Play version of Termux is not anymore updated).
2. Install Ubuntu 20.04 with proot in Termux (you can use [AnLinux](https://f-droid.org/en/packages/exa.lnx.a/) (free software) or [proot-distro](https://github.com/termux/proot-distro) (free) or [Andronix](https://andronix.app/) (not completely a free software) to automate the process). Andronix seems to have the most convenient user experience.
3. Now install a desktop environment (XFCE worked for me), and set up a VNC server (Anlinux and Andronix can automate these tasks for you). To start a new XFCE session, enter the command `vncserver-start`.
4. Install a VNC viewer app in Android, e.g. [androidVNC](https://f-droid.org/en/packages/android.androidVNC/) (free software), or [VNC viewer](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android&hl=en_US&gl=US) (non-free). VNC viewer is more convenient to use.
5. Install Foliate (I used the [stable PPA](https://github.com/johnfactotum/foliate/#distribution-packages) in Ubuntu). Snap packages [do not work](https://github.com/termux/proot/issues/58) in proot, I have not checked flatpak.
6. The Foliate .desktop file needs to be edited, to [prevent sandboxing](https://github.com/johnfactotum/foliate/issues/393#issuecomment-635850217) (which Android does not allow for some reason). You may find [Hacker's Keyboard](https://raw.githubusercontent.com/klausw/hackerskeyboard/master/hk-5row-en-s.png) very helpful to edit files in a small screen. It is available in [F-Droid](https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/) as well as in the Play Store.
Open the .desktop file of Foliate (`nano /usr/share/applications/com.github.johnfactotum.Foliate.desktop`), and edit the `Exec` entry to
`Exec=WEBKIT_FORCE_SANDBOX=0 com.github.johnfactotum.Foliate %U`
and, for the library view (at the end of the .desktop file),
`Exec=WEBKIT_FORCE_SANDBOX=0  com.github.johnfactotum.Foliate --library`

(Note: In later versions, you may have to do `WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1` instead.)

You may want to keep the modified .desktop file in your desktop, as you would need to copy it to `/usr/share/applications` every time Foliate is updated to a new version.

(I found that adding `WEBKIT_FORCE_SANDBOX=0` to .bashrc **does not** work here).

To run Foliate after installation
--------------------------------------
Once installation is done,
- Open Termux
- Start Ubuntu
- Start VNC Server
- Open VNC viewer app in Android
- Enjoy your favorite books in your favorite ebook reader.
- When closing, first close Foliate, then turn off the vncserver (`vncserver-stop`) in Termux, and then close ubuntu (`exit` in Termux shell).
If you forget to close vncserver before closing Ubuntu, you may have to manually remove the lockfile for vncserver, before you can start VNCServer once again.

Screenshots
------------------------
### Portrait mode (Foliate in full screen)
![IMG_20210319_205447_resized](https://user-images.githubusercontent.com/3063132/111808031-9ac88980-88f9-11eb-9c19-93a0039385ad.jpg)


### Landscape mode
![1616164471826_resized](https://user-images.githubusercontent.com/3063132/111808075-a6b44b80-88f9-11eb-9a60-9a34b51f4452.jpg)

![1616164471836](https://user-images.githubusercontent.com/3063132/111808114-b16ee080-88f9-11eb-9933-733646e58c74.jpg)
![1616164471847](https://user-images.githubusercontent.com/3063132/111808350-ef6c0480-88f9-11eb-8cc8-d724b70c134d.jpg)



Additional tips/comments:
-----------------------------------------
- You can set a custom resolution, which suites your screen size. For me, the fonts were too small with the default (`1900x1200`) resolution, and I changed it to `1500x700` in my 6.5 inch phone.
- You can also appropriately set the custom resolution to fit your device in portrait mode (eg. `700x1500`), and use Foliate in single column mode (only RealVNC seems to properly support the portrait mode)
- You can set Foliate to full screen
- Ubuntu + XFCE + Foliate consumes ~ **1.2 GB** of storage, and **300 MB** of RAM. It may be less if you use a window manager like i3 instead of XFCE, but I have not tried that.
- You can install your favorite GTK theme to make Foliate (and other apps with CSD) look native on XFCE.

What works:
-------------------------------------
Opening local books, downloading books from OPDS catalogues, library, dictionary, themes, font size, two column/ single column view, touch to turn page, text-to-speech, **basically everything**. Text-to-speech works (tried `epeak-ng`) only after [enabling sound](https://docs.andronix.app/hardware/sound). I had to use some [special tweaks](https://askubuntu.com/a/1336107/124466) to use gTTs.

### What does not work:
- Two finger swipe/pinch to zoom - This is due to limitation of the VNC viewer apps, which do not seem to support multi touch. It is **not** a Foliate bug.
- Double click to open books sometimes does not work. The workaround is to open books from Foliate's "open" menu. Termux can access your phone's internal storage.
 
Why Ubuntu?
--------------------------------------
I chose Ubuntu due to its relatively less download size, and because it worked.
_**Feel free** to add workarounds for your favorite distro in subsequent comments._

While Alpine is very small in size (<300 mb with XFCE and Foliate) Foliate [keeps loading books forever](https://imgur.com/a/OKtycGs) for some reason despite editing the .desktop file.
Arch/Manjaro consume a [lot more space](https://github.com/Hax4us/TermuxAlpine#size-comparision) compared to Ubuntu, but I have verified that Foliate **also works in Arch**.

Feel free to post suggestions/enhancements.

**Comment by apandada1** [comment]
This is a workaround for https://github.com/johnfactotum/foliate/issues/336
I tried to build it natively in Termux (without proot) with meson, but gjs is not available. I then tried to build gjs from source, but it depends on gobject-introspection, which is [yet to be available](https://github.com/termux/x11-packages/issues/81) on Termux. Once it is available, Foliate may be natively installed in Termux (where XFCE and VNC server are already available), which would make the process simpler, and consume less disk space.

Meanwhile, if you are able to somehow compile Foliate/gjs/gobject-introspection natively on Termux, do let us know, and send a pull request to Termux packages.
