### ISSUE TITLE
[Keybinding] Press tab to open index and navigate with vim keys.

### ISSUE THREAD

**Issue by blackCauldron7** [johnfactotum/foliate#740]
**Is your feature request related to a problem? Please describe.**
Press tab to open index and navigate with vim keys.

**Describe the solution you'd like**
Add a keybinding such that `tab` key opens that index thing on the top left of the screen and rather than clicking items, we could select the items with `hjkl` keys.

**Describe alternatives you've considered**
using `xdotool` to send mouse events on keypress but its a messy hack.

**Additional context**
Thanks for the amazing app.

**Comment by johnfactotum** [comment]
I don't think we will ever bind <kbd>Tab</kbd> to anything, because it's already used (by GTK) for moving keyboard focus.

There are already two shortcuts, <kbd>F9</kbd> and <kbd>Ctrl</kbd>+<kbd>T</kbd>, that one can use to open the table of contents (which I assume is what you mean by "index"). From there you can select items with arrow keys, and then press <kbd>Return</kbd> to activate the item.

**Comment by blackCauldron7** [comment]
Thanks i didn't know that is there a keybindigs list somewhere?

**Comment by johnfactotum** [comment]
There's a shortcuts window, which can be opened with <kbd>Ctrl</kbd>+<kbd>?</kbd> (equivalent to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>/</kbd> on a normal US keyboard), or by clicking on the primary menu (<kbd>F10</kbd>) and select "Keyboard Shortcuts".

**Comment by blackCauldron7** [comment]
Can the vim keys for navigation of TOC be added atleast?

**Comment by johnfactotum** [comment]
Well, I suppose it's possible, technically, but it's a bit too much work for a niche use case. It would also conflict with the view's type-to-search functionality (which is broken at the moment; nevertheless, the two features conflict with each other). It would probably be best solved by GTK itself or at least a common GTK library like libadwaita, because the Vim keys would be useful for all list widgets, not just the TOC.
