### ISSUE TITLE
Gutenberg Catalog broken again

### ISSUE THREAD

**Issue by joshbowyer** [johnfactotum/foliate#741]
**Describe the bug**
Trying to view certain catalog results from search, such as authors, returns "Unable to load OPDS feed"

**Version:**
 - Foliate version: 2.6.1
 - OS/Distribution and version: Debian 10
 - Desktop environment: Cinnamon
 - Installation method: .deb file from releases

#419 is the exact same issue but was closed for a weird reason? And the fix seems to have been reverted. Maybe the reason for WebKitGTK not accepting the SSL cert should be looked at?

**Comment by johnfactotum** [comment]
Browsing and searching Project Gutenberg catalogs is fully working for me. It seems those parts are working for you, too. So I think we can rule out certificate problems.

The only thing that isn't working is searching for authors and subjects, which seems like a Project Gutenberg problem, because those pages* are just returning 403.There's nothing we can do about it. I suppose what we _can_ do is check the status code and show a more informative error message.

*See for example, the search result page, http://m.gutenberg.org/ebooks/search.opds/?query=test, which links to https://www.gutenberg.org/ebooks/authors/search.opds/?query=test and https://www.gutenberg.org/ebooks/subjects/search.opds/?query=test, both return a 403 error.
