### ISSUE TITLE
page-break-after doesn't work

### ISSUE THREAD

**Issue by ell1e** [johnfactotum/foliate#759]
**Describe the bug**
`page-break-after` doesn't work. See this test file:

[test.epub.zip](https://github.com/johnfactotum/foliate/files/6796716/test.epub.zip)

**To Reproduce**
1. Download [test.epub.zip](https://github.com/johnfactotum/foliate/files/6796716/test.epub.zip)
2. Open it in foliate

**Expected behavior**
Minimum of three pages, like in okular:
![threepages](https://user-images.githubusercontent.com/64124388/125191280-ddfc8e80-e241-11eb-8014-08cf85b51aae.png)

**Screenshots**
Foliate shows a single page with not even any extra spacing, which is wrong:
![wrongsinglepage](https://user-images.githubusercontent.com/64124388/125191316-0c7a6980-e242-11eb-8d55-fd644fb7ebef.png)

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: flatpak on fedora
 - Desktop environment: GNOME
 - Installation method: flatpak

**Additional context**
These page breaks can be vital if they are scene breaks and if missing may turn a book borderline unreadable. One of my EPUBs also has a dedicated (supposedly, not in foliate) trigger warning page to make sure people don't miss it, and in foliate it's glued and therefore easy to miss as part of other unimportant front matter because the page break to make it stand out doesn't work at all. So the result of this can be high impact.

**Comment by johnfactotum** [comment]
This is known and unfortunately there doesn't currently seem to be a way to fix this because breaking in CSS multi-column layout (which is what Epub.js uses to paginate the book) isn't supported in WebKit (or most other browser engines) yet.

I think a somewhat hacky solution might be to preprocess the file and split up the page into multiple HTML files before rendering it with Epub.js. That would also help alleviate the performance problems of using CSS multicol.

**Comment by johnfactotum** [comment]
This has been fixed in the gtk4 branch with https://github.com/johnfactotum/foliate-js/commit/b8049952bfdafa6563cfc32a1087b30815c2a773.
