### ISSUE TITLE
Trying to add my entire book collection all at once fails with too many files open

### ISSUE THREAD

**Issue by i30817** [johnfactotum/foliate#779]
**Describe the bug**
This happens:
(com.github.johnfactotum.Foliate:58343): GLib-ERROR **: 05:46:13.177: Creating pipes for GWakeup: Too many open files
xargs: foliate: terminated by signal 5

after `find . -type f | xargs -d '\n' foliate --add`

**To Reproduce**
1. Have about 4832 files in a directory (not sure if nautilus is counting directories)
2.  `find . -type f | xargs -d '\n' foliate --add` in that directory
3. stops at 28% for me.

**Expected behavior**
Probably shouldn't blow up just because you pass in a directory with too many files.

**Screenshots**

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Ubuntu 20.04.3 LTS
 - Desktop environment: 3.36.8
 - Installation method: snap

**Additional context**
Many of the files are just rar files with random other formats inside (including gutemberg txt files, old old rtfs or docs or html files) and some of them are calibre extracted zips (with a 'htmlz' extension) of epubs because i didn't want to make the reader i did a few years ago support epubs (it's this thing btw: https://github.com/i30817/bookjar )

So i'd be thankful if this reader supported that kind of thing was supported, though i suspect it will not be - it was painful to support in that reader and i doubt you're going to bother considering how ebooks standardized on epub and mobi meanwhile.

**Comment by i30817** [comment]
Foliate actually can't add any of my files one by one because they're not epubs or mobis but just plain zips or rars with html, 'htm', txt or rtf inside. So that's a failure for me too.

**Comment by johnfactotum** [comment]
Closing as it doesn't support adding books anymore. To add books to the library you must open them manually.

As to the reason why this happened in v2, if I have to guess this must be due to the webview not being destroyed and/or the file not being closed after importing. Looking at the code it does destroy the GtkOffscreenWindow after opening but I don't know if that's enough to actually clean up everything. Could also be related to how WebKit fetches the file.

Probably if it ever regains the ability to add books it should reuse the same WebView. And it now uses `File` objects so the performance should be much better. But then there's even more uncertainty as to when the file gets released by WebKit. A better approach would probably be to just use Tracker to index the files instead.

**Comment by i30817** [comment]
Too bad, not the screen reader for me then. Adding files one by one is ... Well, a deal breaker

**Comment by johnfactotum** [comment]
To be fair, you can open multiple files at once. "Importing" was kind of pointless, anyway. It didn't do anything apart from having the book appear in Foliate's library view. It's exactly the same as opening. It doesn't even use less resource compared to opening. It doesn't copy or index the files, and it won't track changes made to those files, etc.

I still feel that using Tracker could be the answer. See also #730. But too bad that it doesn't (1) generate thumbnails and (2) support Mobipocket/Kindle files. Integrating it with the existing data could also be problematic especially since I don't want to remove the ability to access the data as plain JSON files.
