### ISSUE TITLE
Error opening ePub

### ISSUE THREAD

**Issue by wooque** [johnfactotum/foliate#819]
**Describe the bug**
Trying to open this epub just shows endless loading indicator
https://drive.google.com/file/d/1JO7altM94uq2OMbr_dZCKbJ5njQCarNO/view?usp=sharing
MuPDF open this file fine

**To Reproduce**
1. Try to open provided ePub

**Expected behavior**
ePub opens

**Version:**
 - Foliate version: 2.6.3
 - OS/Distribution and version: Arch Linux
 - Desktop environment: GNOME 41
 - Installation method: official repo

**Comment by BHALUU** [comment]
I have the same issue. The ebooks keeping showing loading indicator and online catalog also keeps loading same as #789 .

OS: POP!_OS 21.04
DE: GNOME 3.38.5
Flatpak aplication: Foliate 2.6.3

![Ebooks keep loading](https://user-images.githubusercontent.com/54549044/145676898-ca346707-1bbb-41a0-b3ed-cd0136806e5a.png)

**Comment by johnfactotum** [comment]
Need to investigate further, but I _think_ this is related to `Text/part0000.xhtml` in the book being HTML rather than XHTML.

**Comment by johnfactotum** [comment]
Now in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch, with #699 fixed, the book opens fine.

There are two other things still broken with this book:

1. The .ncx file contains an unescaped `&`, making it invalid XML.
2. The page sets `charset=macintosh` for some strange reason. In reality the file appears to be UTF-8 encoded.

These will have to be fixed by editing the book.
