### ISSUE TITLE
TOC cannot be resized

### ISSUE THREAD

**Issue by logrusx** [johnfactotum/foliate#825]
Please make Table of contents resizable. 
On higher definition screens with font scaling, it can't fit the titles text.
It would also be nice if it could be docked, especially if it could be on the right.

**Comment by crispinb** [comment]
Just to expand a bit on this issue - I always need to go to the TOC page within the book, as foliate's own TOC only shows me 2 or 3 words of each section title, which is rarely sufficient to browse & navigate.

**Comment by johnfactotum** [comment]
Currently the workaround would be to enable the sidebar, which can be resized, which is more convenient to use if one jumps through the TOC a lot, anyway.

But, after it's ported to libadwaita, it will switch to AdwFlap, which is going to be problematic because, unlike GtkPaned, it can't be resized. I guess one can only hope that a better sidebar widget would be available in libadwaita in the future.

Or I guess the labels could just wrap instead. That'd be another option to consider.

**Comment by crispinb** [comment]
Thanks - actually I much prefer the sidebar.  I just hadn't come across it in the prefs. Shame it's going to be nuked by an update. If possible there ought to be *some* way of seeing the full title, so wrapping or some hover text (whatever is possible with the new widget) would seem to be worth pursuing.

**Comment by johnfactotum** [comment]
> Shame it's going to be nuked by an update.

Well, AdwFlap is a sidebar. It's responsive, and it has nice animations. It just can't be resized (not easily, anyway; might be possible to add it manually, though it really ought to be built into libadwaita), which is unfortunate. I guess one could also look into whatever widget Builder is using in GTK 4.

> some hover text

It already shows the full text on hover, whether sidebar is enabled or not.

**Comment by logrusx** [comment]
I just unmerged Foliate. It hasn't been working for quite a while either way. From what I read here it looks like I won't be using it in the future too, so you can do whatever you decide with this issue.

**Comment by johnfactotum** [comment]
Fixed in the [`gtk4`](https://github.com/johnfactotum/foliate/tree/gtk4) branch.
