### ISSUE TITLE
Support for framebuffer device / eink device

### ISSUE THREAD

**Issue by umaluti1** [johnfactotum/foliate#834]
**Is your feature request related to a problem? Please describe.**
Can foliate run on framebuffered device?

**Is there is a plan to support framebuffer devices?**

**Comment by johnfactotum** [comment]
No idea. It probably already can as long as you can get GTK to work on your device. You'd want to set the GTK theme to high contrast and disable animations (`gsettings set org.gnome.desktop.interface enable-animations false`).

I wouldn't recommend it, though, if the device doesn't have a lot of RAM (which it probably doesn't) because Foliate currently reads and unarchives the whole file in memory. I'm planning on changing this, but it would require either heavily patching or more likely moving away from Epub.js (it's possible to use Epub.js in a more memory efficient manner, but currently there are a couple of bugs that blocks this). See also #813. Apart from the performance issues in Epub.js and JSZip, there are also a number of other performance issues in Foliate that would make it unsuitable for e-ink devices.

Also I'm changing the label into "question" because the issue is currently not actionable. If there are specific bugs or features, feel free to open more specific issues or requests.
