### ISSUE TITLE
Text to Speech

### ISSUE THREAD

**Issue by pwd-github** [johnfactotum/foliate#85]
Please add the ability to have epubs read aloud.

Preferably using speech dispatcher at max speed.

**Comment by johnfactotum** [comment]
Would be nice if this could be done with the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis). Unfortunately it doesn't look like this is currently supported by WebKitGTK, or I least I couldn't find a way to enable it. `window.speechSynthesis` just returns `undefined`.

Otherwise one would have to interact with speech-dispatcher directly, which I imagine would be a lot more inconvenient.
