### ISSUE TITLE
Cannot change the font size.

### ISSUE THREAD

**Issue by mehant-kr** [johnfactotum/foliate#866]
After an update from Kde neon 5.23 to 5.24, I discovered that foliate opens with small fonts. Changing the fonts size from options menu don't work. `Ctrl++/-` shortcuts don't work either. I tried installing flatpack, snap pakages but nothing works.

![foliate_un-changable-font](https://user-images.githubusercontent.com/33193638/153250707-6e907dd1-007a-4377-a1fd-dfcaad81d8da.png)

**Comment by ngirard** [comment]
I'm experiencing the same problem here on Kubuntu 21.10.
This seems to me like the cause is the same as #865.

**Comment by ngirard** [comment]
I managed to restore the correct font size at the price of overzooming the UI by
1. installing a deb package
2. executing
    ```sh
    env GDK_DPI_SCALE=2.0 /usr/bin/com.github.johnfactotum.Foliate <file.epub>
   ```
@mehant-kr, could you please try & report back ?

**Comment by ngirard** [comment]
Turns out that on my machine, this was caused by `Xft.dpi` erroneously set to 0:
```sh
xrdb -query | grep dpi
Xft.dpi:        0
```
A direct forkaround consists in
1. Adding `Xft.dpi: 96` to `~/.Xresources`
2. Executing `xrdb -merge ~/.Xresources`

However, this is not a satisfactory solution: I couldn't pinpoint what caused `Xft.dpi` to be set to 0 in the first place.

Furthermore, this is not an acceptable solution to this issue. Indeed, since
> The X _server DPI_ is, on the other hand, barely used. Common GUI toolkits like Qt and GTK don't care about that setting, not even a little. Icons and things like that won't change.
> — [src](https://linuxreviews.org/HOWTO_set_DPI_in_Xorg)

the expected behaviour of Foliate and its underlying libs here should be to fall back to the value of 96, which is today's tookits choice.

**Comment by mehant-kr** [comment]
I don't know what exactly happened but Creating `~/.Xresources` file and adding `Xft.dpi: 96` to it did the job.
Thanks @ngirard
