### ISSUE TITLE
Foliate doesn't apply embed font in ePub file

### ISSUE THREAD

**Issue by alet** [johnfactotum/foliate#875]
Foliate doesn't apply embed font in ePub file

The ePub of MWE is in attach. Then it opened the result on image result.png
![result](https://user-images.githubusercontent.com/758903/158588000-73e30c12-d103-4711-8d7a-cf50a10f5a47.png)

The expected result on image expected.png (from other reader)
![expected](https://user-images.githubusercontent.com/758903/158588041-5f8bcea2-a1f7-4069-9fac-bbbb803c1945.png)

 - Foliate version: 2.6.4
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: i3wm
 - Installation method: ppa

The text is in Church Slavonic.
The MWE (changed type to zip):
[mwe.zip](https://github.com/johnfactotum/foliate/files/8262012/mwe.zip)

**Comment by johnfactotum** [comment]
You need to check primary menu > *Advanced* > *Use Publisher Font*. By default it will try to force the custom font.

Relabeling this as *question* as it's not exactly a bug. I think in the next major version we should probably change the default to using the publisher font. The main reason for the current default is that people generally expect changing the custom font to have an effect. I guess the real problem is that the "Use Publisher Font" option needs to be put immediately next to the font chooser button. The menu isn't very well organized in general.

**Comment by alet** [comment]
Thanks, it works.

I tried Okular before Foliate and it seems no such setting in Okular. So I didn't look in deep settings of Foliate
