### ISSUE TITLE
ePub location count makes it look like Foliate is skipping pages

### ISSUE THREAD

**Issue by jleonardfl** [johnfactotum/foliate#900]
When reading ePub files, the page numbers displayed don't correlate to page turns by the user.  For example, different window sizes cause the number of "pages turned" to increase, since more content is displayed.  This doesn't harm Foliate's ability to act as an e-reader, but before I figured out what was going on, I thought Foliate was skipping big sections on every page turn.

Ideally, one page turn input by the user would increment the page number by 1.  In order to do this, Foliate would have to respond to changes in window size by recalculating the number of on-screen pages the book's content would fill, and recalculating which page the user is viewing.

The above solution is probably overkill, but it would be nice to have some sort of indication that the page count number is actually an ePub location number.

**Comment by johnfactotum** [comment]
See #175 

> Ideally, one page turn input by the user would increment the page number by 1.

This isn't really feasible for performance reasons. Paginating the whole book, at least with the method it's currently using (CSS columns), will take way too much time and resource. Even rendering a single section (i.e. chapter, or spine item) is often painfully slow.

Since a chapter is already always fully paginated, though, it's possible to show, at no performance cost, an accurate count of on-screen pages within a chapter. That is, something like "Page 12 of 34 in chapter". Some people might find this useful, though it's probably even more confusing than showing "locations".

> it would be nice to have some sort of indication that the page count number is actually an ePub location number.

Maybe in the footer it should say something like "Loc 12 of 345" instead of just "12 of 345". Elsewhere the number is always referred to as "location", not "page".

Technically, the "locations" are currently based on text node character counts. In the future I'd like to switch to a byte-based count instead. The current method of counting text requires loading and processing the whole book, which is quite slow (and the reason why the result is cached). Counting locations based on raw file sizes, while less accurate, can be done instantly.

**Comment by mirrorwolf** [comment]
Hm... From back when we used iBooks, I seem to recall it calculating page numbers in the background (took a few seconds every time you opened the book or changed the font). Would it be feasible to do that here, cache the result, and just display a "..." while it's loading?

It probably all depends on how slow is "slow".

-- Frost

**Comment by johnfactotum** [comment]
It's true that iBooks does it. But if I have to guess, they're probably using some internal API that doesn't involve fully rendering everything. Rendering everything might work for some books but it's probably not worth the performance hit.

Caching wouldn't really work either. For one, the number of pages can actually change not only when you resize the window, but it actually changes as the page loads. You could try to wait for a brief amount of time, or try to guess if the size has stabilized, but I don't believe there's a truly reliable way.

What's more, the size can also change when you interact with the page. This can happen even without scripting or CSS, e.g. when expanding a `<details>` element. So if you expand a `<details>` on the current chapter, the total number of page would increase. But what happens when you go to the next chapter? Since the state is not preserved when you reload a chapter, you will always have to skip page numbers in this case, either when going *to* the next chapter, or when going back *from* the next chapter.

It's not impossible, but IMHO it's just not worth it.

---

In the `gtk4` branch, it now counts bytes instead of words as mentioned in my comment above, so unlike before, the location is always available instantly when you first open a book. It's less accurate, but it works okay in most cases.

The footer now shows "Loc XXX of XXX", so there should be less confusion, so I think this issue is resolved. It also shows the real, physical print version page number, if available, as "Page XXX of XXX".

**Comment by user-1-2-3-4-5** [comment]
Is it possible to disable the "location" book progress tracking? Chapters are enough for most books and I prefer not to actively keep track of how far I've progressed.

    Loc. 155 of 322

<img width="1192" height="94" alt="Image" src="https://github.com/user-attachments/assets/e94baa23-6b73-48d8-89cb-bcc37af66027" />

---

**EDIT** I don't want to disable to [interactive progress bar](https://github.com/johnfactotum/foliate/issues/175#issuecomment-553254359), only the always-displayed location marker.

**Comment by johnfactotum** [comment]
Currently no, it's not customizable. In v2 you used to be able to change it to show nothing.
