### ISSUE TITLE
How can I purge *all* settings?

### ISSUE THREAD

**Issue by tomicakorac** [johnfactotum/foliate#919]
**Question:**
How can I remove any and all traces of Foliate having ever existed on my system?

The issue I'm facing:

- I uninstall Foliate (apt purge foliate)
- I search system-wide for \*(F|f)oliat\* and permanently delete each and every instance of found results
- I re-install Foliate (apt install foliate)
- My old app settings are magically back!

I want to nuke *all* of Foliate data and make a clean install. How can I do that? Which are all the places that Foliate uses to store config, cache, data and any other traces of its existance?

**Version:**
 - Foliate version: Latest
 - OS/Distribution and version: Ubuntu 22.04
 - Desktop environment: GNOME Shell 42
 - Installation method: PPA

**Comment by johnfactotum** [comment]
Run `gsettings list-recursively com.github.johnfactotum.Foliate`.

Or use dconf Editor, navigate to `/com/github/johnfactotum/`, right click on `Foliate`, and select "Reset recursively".

**Comment by tomicakorac** [comment]
Thank you.

**Comment by in-in** [comment]
```bash
gsettings list-recursively com.github.johnfactotum.Foliate
No such schema “com.github.johnfactotum.Foliate”

```

**Comment by johnfactotum** [comment]
`list-recursively` was a typo. Should be `reset-recursively`.

"No such schema" means that GSettings is not aware of the settings, because the schema isn't installed. This could happen if
1. You've uninstalled Foliate, in which case you should run it after reinstalling.
2. You're running Foliate without installing, in which case you need to run `gsettings` with the `--schemadir` option with the schema directory that you're running Foliate with.
3. You're using Flatpak, in which case you need to either run `gsettings` inside the app's sandbox, or you can just edit or delete `~/.var/app/com.github.johnfactotum.Foliate/config/glib-2.0/settings/keyfile`.

Alternatively, in the first two cases, use dconf-editor, with which you can purge the settings whether the schema exists or not.
