### ISSUE TITLE
Overriding left alignment

### ISSUE THREAD

**Issue by Eliclax** [johnfactotum/foliate#924]
**Question:**
One of my books doesn't seem to want to justify, even when ticking the "Full Justification" button.  Is this because left alignment is built into the epub?  If so, is it possible to override this behaviour?  (I am able to justify the text on the same file using ReadEra on my phone.)  I can provide the epub if necessary.

Thank you very much!

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Ubuntu 20.04
 - Desktop environment: Plasma KDE
 - Installation method: download .deb file from Github and run installer

**Comment by johnfactotum** [comment]
Currently it only sets `text-align: justify` for `p`. So it won't work if the book's stylesheets has anything more specific than that. And I don't think we can set anything more specific than that because it's very common to have center- or right-aligned (or more precisely, end-aligned) paragraphs, which would break if one tries to override anything.
