### ISSUE TITLE
Flathub version 2.6.4 unreliable/fails-to opening /run/user/{uid}/doc/{id} books.

### ISSUE THREAD

**Issue by rwperrott** [johnfactotum/foliate#942]
**Describe the bug**
A re-open or library open of a /run/user/{uid}/doc/{digits} file, always fails for the Flathub version, after a prior successful open from calibre, and shows this in the middle of the window:

"Could not open file"
"file not found"

I tried using Flatseal, to set Flatpack permissions, as follows, "All users file" turned on and adding /run/user/{uid}/doc to "Other Files", but it didn't help.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pick a EPUB book in calibre.
2. Right click on "EPUB" in the "Formats" row.
3. Select the "Open With" menu item and ensure that Foliate was added as one of the "Open With" programs.
4. Select Foliate to open the book with.
5. It then hopefully opens the file, assuming it doesn't bug spin-forever, including for Sigil validated EPUBs.
6. If the book did open, close foliate, the reopen foliate directly.
7. See the bug, as above.

**Expected behavior**
Always be able to open a known existing book file, unless it has a critical structural error, or is genuinely missing.

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Linux Mint 21 MATE 64-bit
 - Desktop environment: MATE
 - Installation method: Flatpak

**Additional context**
The Flathub version of Sigil seems to have trouble opening EPUBs from calibre or directly from previous files.

If it requires additional Flathub permission tweaks, to fix the Foliate issue, please specify what these are.

As it stands the Flatpack version is useless to me, so I'll have to continue using the deb version, and keep reinstalling for each new Foliate and OS version.

**Comment by johnfactotum** [comment]
Yes, the files exported via the document portal is not persistent.

I'm not sure you could export documents persistently at all with Flatpak. Maybe one could try exporting them with [flatpak-document-export](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-document-export), which I'm guessing might default to persistent exports because there's a `--transient` option. (I have not tried this, though.) And I'm not sure if there's some other Flatpak configuration that could solve this problem.

One way to sort of work around this this would be to use Tracker. And that is probably better anyway for people who use Foliate to directly open files (as opposed to always launching Foliate from another app like a file manager) because it also handles the situation where the file is renamed or moved. However that will of course require one to index files with Tracker. Also I just realized that I forgot to add `--talk-name=org.freedesktop.Tracker3.Miner.Files` in the Flatpak manifest, which I think is needed for reading the system's Tracker database in Flatpak.

**Comment by johnfactotum** [comment]
Upstream issue: https://github.com/flatpak/xdg-desktop-portal/issues/133

**Comment by nathanal** [comment]
I'm not sure if I'm experiencing the same issue (don't use calibre), but this doesn't seem to happen when you open via Foliate (press the + then use the File open dialog), not ideal but beats reopening every time.

When opening the file by double-clicking in a File Explorer, it launches Foliate with `--file-forwarding` which explicitly does not make the files persist (ref: https://docs.flatpak.org/en/latest/flatpak-command-reference.html ). 

Update: should mention the upstream issue is closed as a duplicate to a different issue and this workaround was mentioned in one of the linked issues

**Comment by rwperrott** [comment]
It doesn't appear to be present currently, so closing.
