### ISSUE TITLE
copy text in markdown

### ISSUE THREAD

**Issue by cs-mshah** [johnfactotum/foliate#954]
Currently copying text on selection just copies the underlying plain text. This reduces the functionality when there are underlying clickable links which should also be copied. 
It would be great if the copy also copies the text in markdown format, preserving the links.

Also, having markdown in the comments for the annotations would be great.

**Comment by johnfactotum** [comment]
The correct behavior would be to copy both plain text and HTML. And that would already be handled if we could use the built-in copy action from the WebView's context menu. The problem is that I don't know if there's a way of accessing or trigger the context menu from selection. Otherwise we must extract the HTML ourselves, which, lest I forget, can be done by serializing the document fragment:
```js
const fragment = range.cloneContents()
const html = new XMLSerializer().serializeToString(fragment)
```

>Also, having markdown in the comments for the annotations would be great.

Technically speaking, you can already do that. The idea of markdown is precisely that it is usable as plain text. Adding rich text is going to introduce a lot of complexity that I doubt is going to be worth the effort.
