### ISSUE TITLE
Doc files : wouldn't it be nice ?

### ISSUE THREAD

**Issue by bouboulov** [johnfactotum/foliate#966]
I have been writing a SlackBuild for the Slackware Linux distribution but to be fully accepted it would need doc files.

So i think it would be a nice enhancement.

Thanks for that great reader :)

**Comment by johnfactotum** [comment]
I'm not sure what you mean by "doc files"?

**Comment by bouboulov** [comment]
They are standard files in old Linux systems, maybe i could make them my own but I don't know, i'm just beginning with this.

Typically they are stored in /usr/doc or /usr/share/doc

[Doc files usage](https://www.eukhost.com/blog/webhosting/usage-of-usrdoc-directory/)

**Comment by johnfactotum** [comment]
I will close this as won't fix for now, since there aren't really any plans to add them, and I doubt people will read them. IIUC those docs are more intended for libraries or command line programs. If you absolutely need something to put there, you can copy the documentation from README.md or the Wiki.
