### ISSUE TITLE
Option for selection without default for note

### ISSUE THREAD

**Issue by mlouielu** [johnfactotum/foliate#98]
Hi there,

After testing many e-readers for Linux/epub with lots of frustration, I found foliate, and it works quite good for myself. Deeply thanks to you @johnfactotum.

Currently, foliate's selection is default to adding a note on it. But in my scenario, I sometimes use cursor selection to read through what I'm reading, what I have thought is:

1. Make an option to enable/disable the current function
2. Let right press dragging as selection without adding a new note

I'm familiar with GTK, but not with javascript one, is this possible to do with?

Thanks!

**Comment by itprojects** [comment]
+1 Same here.

**Comment by johnfactotum** [comment]
Now it shows a popover to offer to highlight/lookup/copy instead of doing highlight/lookup on selection. 

The selection is also now cleared when the popover pops down, so it now takes one instead of two clicks to clear the selection.

An additional gain is that it's now possible to lookup phrases instead of just single words.

Will add the option to restore the previous behavior later.

**Comment by itprojects** [comment]
Works well. The user needs to remember to delete the files in the folder ~/.local/share/com.github.johnfactotum.Foliate/* before upgrading to the new code. Otherwise pop-ups might not show.

**Comment by johnfactotum** [comment]
Deleting files shouldn't be necessary. If so, then it's a bug.

**Comment by itprojects** [comment]
It's more likely that the install in question was broken.
