### ISSUE TITLE
Unreasonably high memory usage

### ISSUE THREAD

**Issue by boehs** [johnfactotum/foliate#982]
**Describe the bug**
First, thanks for this. It's really quite nice. I noticed that foliate seems to be consuming 3-400mb of ram, which seems crazy high. Okular needs a quarter of it, even with the additional features. I'm not sure what is consuming all the memory here.

**Screenshots**

![image](https://user-images.githubusercontent.com/51836263/213831555-d2897cef-6c8d-447d-8c54-f503976a739a.png)

**Version:**
 - Foliate version: 2.6.4
 - OS/Distribution and version: Arch
 - Desktop environment: KDE 5.27-beta
 - Installation method: Arch Repositories

**Comment by johnfactotum** [comment]
The most obvious reason is that the file is loaded and unarchived entirely in memory. See #813. This is fixed in the gtk4 branch with the new renderer. See #962. In short, the new renderer is written precisely to address these issues.

There are probably some other things that could be improved. But those would need to be investigated case by case. Some might be due to GJS, GTK, and WebKit in general, and others might be specific to Foliate. IIRC, a single WebKit process alone could easily use more than 100 mb.

**Comment by boehs** [comment]
> The most obvious reason is that the file is loaded and unarchived entirely in memory. See #813. This is fixed in the gtk4 branch with the new renderer. See #962. In short, the new renderer is written precisely to address these issues.

Yeah, that could very well be it! Excited to see how the gtk4 branch works

**Comment by johnfactotum** [comment]
To compare the stable version with the new version — from my own quick, very unscientific test with GNOME's system monitor, opening a rather large EPUB file, about 210 MB in size:

| version | main GJS process | WebKitWebProcess | WebKitNetworkProcess | total |
|-|-|-|-|-|
| 2.6.4 | ~90 | ~300 | ~200 | ~600 |
| gtk4 | ~90 | ~80 | ~20 | ~200 |

( in MB)

And of course, the old version takes ~20 seconds to open the file. I think it used way more than 600 MB *while* opening the file, because it not only unarchives the entire file, but in fact also parses almost every chapter to get CFIs for the whole TOC.

With the gtk4 branch, it opens under 4 seconds.
